misc/ldap_connect_auth.c

* util/ldaputils.c (ldap_auth_bind): Perform an anonymous bind to
search a DN using the recieved uid as filter. Otherwise use the
received DN.

Backport r29874, by Juan Jose Nicola.

---

util/kb.c
util/kb.h
util/nvticache.c
util/nvticache.h

To be used for nvticache cleanup.

Add nvticache_count() and nvticache_delete()

---

nasl/nasl_grammar.y

Check if the file's checksum is already present in the KB before
attempting to load the checksums file. In master branch, this is insured
by the timestamp check which is not backported in openvas-9.

Fix issue of repetitive loading of checksums file

---

util/nvticache.c

Already defined in util/nvticache.h

Remove duplicate NVTICACHE_STR define.

---

nasl/nasl_grammar.y

On non-fresh load-ups, sha256sums content is only reloaded into Redis
when parsing new plugins. Any modified plugins that were parsed before
that would be verified against old checksum values.

Fix loading of checksums.

---

INSTALL
README.md

* README: Add "gmp" and "osp" in the list.
* INSTALL: Update from Debian "Jessie" 8 to Debian "Stretch" 9
as the defailt development system.

Updating README and INSTALL to latest state.

---

CHANGES

Preparing the openvas-libraries 8.0.10 release.

---

util/serverutils.c
util/serverutils.h

Remove TODOs from util/serverutils.c

Todo serverutils

---

util/gpgmeutils.c
util/gpgmeutils.h

* util/gpgmeutils.c (log_gpgme): Is now global.
* util/gpgmeutils.h (log_gpgme): Add prototype.

Remove TODO.

---

util/nvticache.c
util/nvticache.h

Also fix nvt_feed_version() documentation.

Add nvticache_check_feed().

---

base/kb.h
base/kb_redis.c
base/nvticache.c
base/nvticache.h

Add nvticache_count() and nvticache_delete()
To be used for nvticache cleanup.

Backport PR #20.

---

CHANGES

Preparing the gvm-libs 1.0+beta1 release.

---

util/kb.c
util/kb.h

In order to implement message queues.

Add kb_item_push_str() and kb_item_pop_str().

---

base/hosts.c
base/hosts.h

Attach a source to each vhost value.

---

base/hosts.c
base/hosts.h

Also free source in gvm_vhost_free().

Add gvm_vhost_new().

---

util/kb.c

Fix regression in 94da2b1c5007b9f857b30ea838d5c29dfabfce2d.

Don't quote key value.

---

util/radiusutils.c

Embedded creation of Radius client configs is broken in the versions of
radcli currently packaged by Debian, so as a workaround create the
config using a temp file when using radcli.

Create Radius config from file when using radcli

---

util/nvticache.c

Also refactor nvt_feed_version() code.

Check return value for popen() call.

---

util/kb.c
util/kb.h

* util/kb.c (Add redis_get_kb_index) New function to get the db index.
(redis_direct_conn) New function to connect to redis and select a specific db.

Add redis_get_kb_index() and redis_direct_conn().

---

base/hosts.c

To catch outdated/erroneous entries, verify that a vhost value obtained
through reverse-lookup does resolve to the host's IP address, before
inserting it in the host's vhosts list.

Verify reverse-lookup entry before adding it.

---

util/kb.c

Some benchmarking:
for (a = 0; a < 50000; a++)
{
replace_kb_item(name:"foo_str", value:'bar' + a);
replace_kb_item(name:"foo_int", value:a);
}
$ time openvas-nasl -X test.nasl
Before:
real	0m14.039s
user	0m3.437s
sys	0m3.979s
After:
$ time openvas-nasl -X test.nasl
real	0m3.812s
user	0m1.860s
sys	0m0.584s

Pipeline kb_item_set_int/str() commands

---

CHANGES

Preparing the gvm-libs 1.0+beta2 release.

---

util/kb.c

> for (a = 0; a < 10; a++)
> {
>   set_kb_item(name:'foo' + a, value:'1');
>   set_kb_item(name:'foo' + a, value:'2');
>   set_kb_item(name:'foo' + a, value:'3');
> }
> display(get_kb_list('foo*'));
> for (a = 0; a < 100000; a++)
> {
>   get_kb_list('foo*');
> }
Before:
real	0m23.625s
user	0m6.610s
sys	0m6.692s
After:
real	0m8.446s
user	0m3.989s
sys	0m1.134s

Pipeline kb_get_list() to improve performance.

---

CMakeLists.txt

Now make tests finds the test.

Add the test to CMakeList to be executed by ctest.

---

util/kb.c

Use g_debug() for key already containing value.

---

base/credentials.c
gmp/gmp.c
gmp/gmp.h
util/serverutils.c
util/serverutils.h
util/xmlutils.h

Also remove code that was used for omp-cli support on Windows.

Refactor free_credentials().

---

INSTALL.md
README.md

Move section related to development from INSTALL.md to the contributing section in README.md.
Add subsection "Code style and formatting".

Contributing notes.

---

CHANGES
CMakeLists.txt
README.md

Update CHANGES
Update version: unset beta release.
Update circleci badge.

Preparing for gvm-libs 1.0.0 release

---

.codecov.yml

Just like https://github.com/greenbone/gvmd/pull/349

Disable Codecov Bot commenting.

---

.codecov.yml
base/hosts.c
util/nvticache.c

Backports PRs https://github.com/greenbone/gvm-libs/pull/183 https://github.com/greenbone/gvm-libs/pull/184 https://github.com/greenbone/gvm-libs/pull/185

Backport memleaks

---

util/CMakeLists.txt

Make libhiredis mandatory.

---

util/nvticache.c

Also set initial cache version to 0 instead of 1 for clarity.

Add log message about updated NVT feed version.

---

util/kb.c

Delete old preferences before inserting new ones.
Ref: https://github.com/greenbone/gvm-libs/pull/195

Backport #195

---

CHANGES
CMakeLists.txt
README.md

* CMakeLists.txt: Set version to 10.0.0.
* Update CHANGES.
* Update circleci badge.

Preparing for release gvm-libs-10.0.0.

---

CMakeLists.txt

* CMakeLists.txt: Set version to gvm-libs-11.0+beta1

Post release version.

---

util/nvticache.c

Backport of https://github.com/greenbone/gvm-libs/pull/213

Fix prefs key in nvticache_delete().

---

util/kb.c

Scanner officially supports 3.2 and higher.
See https://github.com/greenbone/openvas-scanner/pull/287

Remove support for Redis 2.4.

---

base/hosts.c

Handle EAI_AGAIN in gvm_host_reverse_lookup() IPv6 case.

---

.circleci/config.yml
.clang-format
base/nvti.c
base/nvti.h

Note that only files in base/ are checked.

Add source code format check to CircleCI

---

CHANGES

Minor typo fixes as a follow-up of the changes done in PR #247

Fix typos in CHANGES file

---

util/kb.c

This helped me to identify a misconfiguration.

Extend redis connection error msg with actual path

---

CHANGELOG.md
CMakeLists.txt

Version bump

---

README.md

Add hint for the release file signatures key to README

---

CHANGELOG.md
util/CMakeLists.txt

Fix missing linking to libgnutls in util/CMakeLists.txt

---

INSTALL.md

Also, libxml2 was missing as dependency.
**Checklist**:

Update install instructions to Debian Buster.

---

util/xmlutils.c

Don't create an entity tree during read_string_c (10.0)

---

util/xmlutils.c

Free string in all error exit cases (11.0)

---

util/kb.c
util/nvticache.c
util/serverutils.c

Make doc spacing more consistent (11.0)

---

CHANGELOG.md
base/hosts.c

[11.0] Fix is_cidr_block().

---

CMakeLists.txt

Change version from 20.04 to 20.08

---

util/kb.c
util/kb.h

Fix doc strings to describe return type properly.

---

util/CMakeLists.txt

Fix
https://github.com/greenbone/gvm-libs/issues/334

GCC need an option for build

---

boreas/CMakeLists.txt
boreas/alivedetection.c
boreas/alivedetection.h
boreas/alivedetection_tests.c
boreas/boreas_error.c
boreas/boreas_error.h
boreas/boreas_error_tests.c
boreas/boreas_io.c
boreas/boreas_io.h
boreas/boreas_io_tests.c
boreas/ping.c
boreas/ping.h
boreas/ping_tests.c
boreas/sniffer.c
boreas/sniffer.h
boreas/sniffer_tests.c
boreas/util.c
boreas/util.h
boreas/util_tests.c

Update header description

---

CHANGELOG.md
base/hosts.c
base/hosts_tests.c

Improve validation in is_hostname

---

base/networking.c
boreas/boreas_error.c
boreas/boreas_io.c
boreas/util.c
util/serverutils.c

Fix various typos.

---

base/hosts_tests.c

Add first tests of gvm_hosts_new_with_max

---

CMakeLists.txt

Raise version to 21.04

---

CMakeLists.txt
boreas/CMakeLists.txt
boreas/boreas_io.c
boreas/cli.c
boreas/cli.h
boreas/cli_tests.c

CLI for Boreas

---

CHANGELOG.md
CMakeLists.txt
boreas/CMakeLists.txt
boreas/alivedetection.c
boreas/boreas_io.c
boreas/cli.c
boreas/cli.h
boreas/cli_tests.c

Merge back into master

---

util/nvticache.c

Log warning if wrong PLUGIN_SET format is supplied

---

CHANGELOG.md
CMakeLists.txt

Prepare 20.8.0 release

---

boreas/cli.c

**What**:
Fix https://github.com/greenbone/gvm-libs/pull/392 for boreas-cli too.
**Why**:
Because it is a bug.
**How**:
Same as in https://github.com/greenbone/gvm-libs/pull/392.
**Checklist**:

Fix port size for boreas-cli

---

CHANGELOG.md
util/xmlutils.c

**What**:
Backport PR #394 
**Checklist**:

[20.08] Retry if response via tls is still not received

---

CHANGELOG.md
INSTALL.md
util/CMakeLists.txt

**What**:
Increase minimum gpgme version
**Why**:
gpgme_key_t->fpr requires 1.7.0
Found in https://github.com/greenbone/gvm-libs/issues/329#issuecomment-628898793.
**How**:
cmake .
**Checklist**:

Increase minimum gpgme version

---

.circleci/config.yml

**What**:
change ci build to use buster and add a dependency: libnet1-dev to build image.
**Why**:
**How**:
**Checklist**:

Change ci to buster

---

INSTALL.md

**What**:
* extend the `INSTALL.md` with additional install information.
**Why**:
* While install process and testing I missed some information here.
**How**:
**Checklist**:

Extend install md

---

base/logging.c
base/networking.c
boreas/boreas_io.c
osp/osp.c
util/serverutils.c

**What**:
Partial backport of https://github.com/greenbone/gvm-libs/pull/428.
**Why**:
General improvement.
**How**:
**Checklist**:

Backport static code analysis fixes

---

CHANGELOG.md
base/networking.c
boreas/util.c

**What**:
More or less replica of https://github.com/greenbone/gvm-libs/pull/398 for fixing https://github.com/greenbone/gvm-libs/issues/397 but with correct branch.
**Why**:
Fix compiler errors.
**How**:
**Checklist**:

Fix Compiler error

---

CHANGELOG.md
CMakeLists.txt

**What**:
**Why**:
**How**:
**Checklist**:

Set version to 21.10

---

CHANGELOG.md
base/prefs.c

**What**:
Fix openvas preference name.
**Why**:
The option was rename to "allow_simultaneous_ips"
**How**:
**Checklist**:

Fix openvas preference name.

---

CHANGELOG.md

**What**:
Prepare for release 21.04.0
**Why**:
**How**:
**Checklist**:

Prepare for release 21.04.0

---

CHANGELOG.md
CMakeLists.txt

**What**:
**Why**:
**How**:
**Checklist**:

Version bump after release

---

.circleci/config.yml
util/gpgmeutils.c
util/ldaputils.c
util/passwordbasedauthentication.c
util/passwordbasedauthentication.h
util/passwordbasedauthentication_tests.c
util/xmlutils.c

**What**:
Add all modules to CI format check
**Why**:
Do not miss wrong formatting.
**How**:
**Checklist**:

Add all modules to CI format check

---

CHANGELOG.md
INSTALL.md
util/CMakeLists.txt
util/mqtt.c
util/mqtt.h

**What**:
Related: https://github.com/greenbone/openvas-scanner/pull/743
Add basic support for mqtt
**Why**:
**How**:
**Checklist**:

Add basic support for mqtt

---

.github/workflows/codeql-analysis-c.yml

**What**:
**Why**:
**How**:
**Checklist**:

Scan C Code GitHub Action

---

base/logging.c
util/fileutils.c

* Replace `localtime` with `localtime_r()`
* Also added logger warning, if `localtime_r` fails
**What**:
**Why**:
* `localtime()` has potential security leaks according to CodeQL
**How**:
**Checklist**:

Replace localtime with localtime_r

---

CHANGELOG.md

**What**:
* Remove the `0` from the `21.4` releases in the CHANGELOG
**Why**:
**How**:
**Checklist**:

Fix version in Changelog

---

CMakeLists.txt

**What**:
* `= 1`
**Why**:
**How**:
**Checklist**:

Set dev version in CMakeLists

---

.github/workflows/ci-c.yml
.github/workflows/codeql-analysis-c.yml
base/hosts.c

**What**:
**Why**:
**How**:
**Checklist**:

Add branch middleware

---

.github/workflows/ci-c.yml
.github/workflows/codeql-analysis-c.yml
CHANGELOG.md
INSTALL.md
base/hosts.c
util/CMakeLists.txt
util/mqtt.c
util/mqtt.h

**What**:
This is reintroduction after rebase.
For details see
Base: https://github.com/greenbone/gvm-libs/pull/505/commits
Fix: https://github.com/greenbone/gvm-libs/pull/511/commits
**Why**:
Separation of feature branch and master.
**How**:
**Checklist**:

Move MQTT feature into new branch

---

.docker/deploy/clang/Dockerfile
.docker/deploy/gcc/Dockerfile
.docker/test/clang/Dockerfile
.docker/test/gcc/Dockerfile
.github/workflows/docker-ci.yml

**What**:
**Why**:
**How**:
**Checklist**:

[gvm-libs-20.08] Add Dockerfile(s) and Build & Upload Workflow

---

.docker/deploy/clang/Dockerfile
.docker/deploy/gcc/Dockerfile
.docker/test/clang/Dockerfile
.docker/test/gcc/Dockerfile
.github/workflows/docker-ci.yml

**What**:
**Why**:
**How**:
**Checklist**:

[gvm-libs-21.04] Add Dockerfile(s) and Build & Upload Workflow

---

.docker/deploy/clang/Dockerfile
.docker/deploy/gcc/Dockerfile
.docker/test/clang/Dockerfile
.docker/test/gcc/Dockerfile
.github/workflows/docker-ci.yml
base/hosts.c

**What**:
* Adding test and deploy Dockerfiles for gvm-libs and a workflow to upload these to https://hub.docker.com/u/greenbone 
**Why**:
**How**:
**Checklist**:

[master] Add Dockerfile(s) and Build & Upload Workflow

---

.github/workflows/docker-ci.yml

**What**:
**Why**:
**How**:
**Checklist**:

Get the branch correctly

---

.github/workflows/docker-ci.yml

**What**:
**Why**:
**How**:
**Checklist**:

[20.08] [docker CI] Use correct reference to branch name

---

.github/workflows/docker-ci.yml

**What**:
**Why**:
**How**:
**Checklist**:

[21.04] [docker CI] Use correct reference to branch name

---

.github/workflows/ci-c.yml

**What**:
**Why**:
**How**:
**Checklist**:

[21.04] [CI] Update docker container in CI

---

.github/workflows/ci-c.yml
CHANGELOG.md

**What**:
**Why**:
**How**:
**Checklist**:

[master] [CI] Update CHANGELOG and Docker containers in the CI

---

.docker/deploy/clang/Dockerfile
.docker/deploy/gcc/Dockerfile
.docker/test/clang/Dockerfile
.docker/test/gcc/Dockerfile
.github/workflows/docker-ci.yml

**What**:
**Why**:
**How**:
**Checklist**:

[middleware] Add Dockerfiles and workflow to upload docker images

---

CHANGELOG.md

**What**:
**Why**:
**How**:
**Checklist**:

[20.08] Update CHANGELOG file

---

CHANGELOG.md

**What**:
**Why**:
**How**:
**Checklist**:

[21.04] Update Changelog file after release(s)

---

.github/workflows/ci-c.yml

**What**:
**Why**:
**How**:
**Checklist**:

[middleware] [CI] Update docker container in CI 

---

.github/workflows/docker-ci.yml

**What**:
**Why**:
* Previously branches like gvm-libs-20.08 have not been detected correctly
**How**:
**Checklist**:

Fix the docker CI branch detection.

---

util/mqtt.c
util/mqtt.h

Remove feature guards.
Add function for single message publish.
Getters and setters.
Reset function.
Init mqtt_t on publish if mqtt_t is NULL.
**What**:
**Why**:
**How**:
**Checklist**:

Refactor MQTT handling

---

.github/workflows/docker-sched.yml
.mergify.yml

**What**:
* Port to Middleware branch
* Scheduled docker builds ...
**Why**:
**How**:
**Checklist**:

QoL Improvements

---

.github/workflows/docker-sched.yml

**What**:
* Put name in quotes...
**Why**:
**How**:
**Checklist**:

Fix workflow

---

.github/workflows/release-pontos-patch.yml
CHANGELOG.md

**What**:
**Why**:
**How**:
**Checklist**:

[21.04] Add signing to workflow ... 

---

.github/workflows/docker-sched.yml

The VERSION variable should not be used, run every day.
**What**:
**Why**:
**How**:
**Checklist**:

Fix the scheduled workflow

---

.github/workflows/docker-sched.yml

**What**:
**Why**:
**How**:
**Checklist**:

Fix scheduled docker builds

---

.github/workflows/docker-sched.yml

**What**:
**Why**:
**How**:
**Checklist**:

Fixing the scheduled workflow ... again

---

.docker/testing/Dockerfile

**What**:
* Using the latest release of cgreen instead of master (in docker)
**Why**:
* Even if stated otherwise cgreen in master is now running ninja as build system per default
* I think using a stable release version is better
**How**:
* Check out correct branch
**Checklist**:

[docker] Fix an issue with cgreen in the docker images

---

.docker/build.Dockerfile
.github/workflows/ci-c.yml
.github/workflows/codeql-analysis-c.yml
.github/workflows/release-pontos-manually.yml
base/pwpolicy.c
boreas/arp.c

**What**:
**Why**:
**How**:
**Checklist**:

[main] Cleanup the CI and set build Dockerfile image to stable

---

.docker/build.Dockerfile
.github/workflows/container-pr.yml
.github/workflows/container.yml

**What**:
Use new container-image-tags action for specifying the container image names. AP-1753
**Why**:
This allows applying our naming rules at one single place.
**How**:
**Checklist**:

Use new container image tags action

---

.github/workflows/container.yml

**What**:
Use correct name for the action
**Why**:
**How**:
**Checklist**:

Fix using the container-image-tags action

---

.docker/build.Dockerfile
.github/workflows/ci-c.yml

**What**:
**Why**:
**How**:
**Checklist**:

[main] Some CI cleanup changes

---

.github/workflows/container.yml

Co-authored-by: Jaspar L. <jaspar.loechte@greenbone.net>
**What**:
**Why**:
**How**:
**Checklist**:

Trigger dependent container build

---

.docker/build.Dockerfile
.github/workflows/ci-c.yml
.github/workflows/container.yml
base/pwpolicy.c
boreas/arp.c

**What**:
**Why**:
**How**:
**Checklist**:

[stable] Cleanup some files in CI

---

CMakeLists.txt
base/array.c
base/array.h
base/cvss.c
base/cvss_tests.c
base/networking.c
base/networking.h
base/networking_tests.c
base/prefs.c
base/settings.c
boreas/CMakeLists.txt
boreas/boreas_io.c
boreas/util_tests.c
gmp/gmp.c
util/CMakeLists.txt
util/authutils.c
util/authutils.h
util/kb.c
util/kb.h
util/ldaputils.c
util/ldaputils.h
util/mqtt.c
util/nvticache.c
util/nvticache.h
util/passwordbasedauthentication.c
util/radiusutils.c
util/serverutils.c
util/xmlutils.c

Refactor: add stricter compile options to find common issues
Add:
-Wextra
-Werror
-Wpedantic
-Wmissing-prototypes
-Wshadow
-Wsequence-point
And set to c11.

additional warnings

---

CMakeLists.txt
base/prefs.c

- Refactor: ignore -Wstringop-truncation due to FOTIFY=2
- Refactor: remove -Werror

unset werror

---

CMakeLists.txt
base/networking.c
base/prefs.c
base/proctitle.c
osp/osp.c
util/kb.c
util/mqtt.c
util/passwordbasedauthentication.c

- Refactor: ignore -Wstringop-truncation due to FOTIFY=2
- Refactor: remove -Werror
- Refactor: enable -Werror replace strncpy with memcpy

replace strncpy

---

.docker/build.Dockerfile
.docker/prod.Dockerfile
.github/workflows/ci-c.yml
.github/workflows/container.yml

**What**:
**Why**:
**How**:
**Checklist**:

[CI/Docker/Deployment] [main] Refactory

---

.github/workflows/ci-c.yml

see #657
**What**:
**Why**:
**How**:
**Checklist**:

Fix CI [see #657]

---

.docker/build.Dockerfile
.docker/prod.Dockerfile
.github/workflows/ci-c.yml
.github/workflows/container.yml
.github/workflows/release-pontos-manually.yml
.github/workflows/release-pontos-patch.yml

>**The release actions has not been tested for now.**
> **So I will use this branch for testing it for the next community release.**
**What**:
* Updated Dockerimages:
* `prod` now builds from `build` instead from debian stable.
* build only uses `gcc` for now
* `gcc` is the `PRODUCTION` build(-> GOS), so this should be mandatory and default for us, too
* removed `clang`
* CI now only tests gcc and installs `clang` in job for scan build
* Use `greenbone/actions/release@v1` for releases (untested)
**What**:
**Why**:
**How**:
**Checklist**:

[CI/Docker/Deployment] [oldstable] Refactory

---

.docker/build.Dockerfile
.docker/prod.Dockerfile
.github/workflows/build-docs.yml
.github/workflows/ci-c.yml
.github/workflows/container.yml
.github/workflows/release-pontos-manually.yml
.github/workflows/release-pontos-patch.yml

**What**:
* Updated Dockerimages:
* `prod` now builds from `build` instead from debian stable.
* build only uses `gcc` for now
* `gcc` is the `PRODUCTION` build(-> GOS), so this should be mandatory and default for us, too
* removed `clang`
* CI now only tests gcc and installs `clang` in job for scan build
* Use `greenbone/actions/release@v1` for releases (untested)
**Why**:
**How**:
**Checklist**:

[CI/Docker/Deployment] [stable] Refactory

---

.docker/build.Dockerfile

**What**:
**Why**:
**How**:
**Checklist**:

Remove `gcc`and `g++` from Dockerfile

---

CHANGELOG.md
CMakeLists.txt

**What**:
**Why**:
**How**:
**Checklist**:

Change 21.10 to 22.4

---

base/hosts.c

**What**:
Make reverse lookup more patient by adding a sleep and increase tries from 2 to 10
**Why**:
Due to 2 really fast consecutive tries the DNS lookup might fail caused by the same (time dependent) error.
**How**:
**Checklist**:

Change: more patient reverse lookup

---

util/kb.c

To connect to TCP the kb->path needs to start with `tcp://` otherwise it
assumes a unix connection.
To test this commit you can run:
```
#include <gvm/util/kb.h>
#define DB_ADDRESS "tcp://localhost"
int main() {
kb_t main_kb = kb_direct_conn (DB_ADDRESS, 1);
kb_item_push_str(main_kb, "test", "Hello world");
g_print("got: %s\n", kb_item_get_str(main_kb, "test"));
}
```
And compile with:
```
gcc $(pkg-config --cflags libgvm_util) test.c $(pkg-config --libs glib-2.0 libgvm_util libgvm_base)
```
This allows openvas to connect to redis via tcp by configuring:
```
db_address = tcp://127.0.0.1:6739
```
within the configuration. If you want to test it via openvas you can run `openvas -u` and verify that the rc is 0.
Resolves #237

Add: possibility to connect to redis via TCP

---

.github/workflows/codeql-analysis-c.yml
.github/workflows/container.yml

**What**:
Build container images for arm64 too
**Why**:
Allow to run our community images on arm64
**How**:
**Checklist**:

Build container images for arm64 too

---

.github/CODEOWNERS
.github/dependabot.yml

**What**:
* Add devops as code owners for github and docker stuff
* Add dependebot for updating github actions
**Why**:
**How**:
**Checklist**:

GitHub settings

---

.github/workflows/container.yml

**What**:
Build container images for pull requests too
**Why**:
Ensure that pull requests don't breake the container builds.
**How**:
**Checklist**:

Change: Build container images for pull requests too

---

util/nvticache.c

**What**:
Don't call SAVE redis command on feed init/upload
Jira: SC-679
**Why**:
**How**:
**Checklist**:

Don't call SAVE redis command on feed init/upload

---

boreas/alivedetection.c
boreas/alivedetection.h

**What**:
Define a better port list and use it
Jira: SC-663
**Why**:
To improve the alive detection.
**How**:
Run a scan. 
**Checklist**:

Define a better port list and use it

---

.github/workflows/release-pontos-manually.yml

**What**:
Use action for release Workflow
**Why**:
The action hides the implementation details.
**How**:
**Checklist**:

Change: Use action for release Workflow

---

base/logging.c
base/logging.h

**What**:
To be able to detect corresponding log messages it is possible to set a reference value, which is then displayed in logs afterwards.
SC-768
**Why**:
**How**:
**Checklist**:

Add: the possibility to set reference value for logs

---

.github/workflows/container.yml

CI: trigger dependent projects that work on a stable branch basis

CI: trigger dependent projects that work on a stable branch basis 

---

base/networking.c
util/kb.c

Fixes #772.
SC-856
Fix glib version check.
Fixes #772.
#772

Fix: glib version check

---

.docker/prod-oldstable.Dockerfile
.github/workflows/container.yml

Adds a new image for gvm-libs based on debian:oldstable.
The tags for that are:
- oldstable - releases
- oldstable-edge - any change

Add: gvm-libs oldstable

---

util/mqtt.c
util/mqtt.h

Support authenticated connection to MQTT broker
SC-917
Improvement

Add: support authenticated connection to MQTT broker

---

base/nvti.c
base/nvti_tests.c

Drop parsing for $Date strings
Jira: SC-903
Not required anymore.

Change: Drop parsing for $Date

---

.docker/prod-testing.Dockerfile

Add: missing dependency in container prod-testing
libhiredis-dev is missing

Add: missing dependency in container prod-testing

---

util/authutils.c
util/authutils.h
util/kb.h

Add function `auth_method_name_valid` to check if an auth method name is valid.
So that `gvmd` can validate user SOURCEs.  See greenbone/gvmd/pull/2205.

Add: function auth_method_name_valid

---

.docker/prod-testing.Dockerfile

Fix CI dependency libssh

---

.github/workflows/push.yml

Fix typo in workflow for creating and pushing testing image
Typo caused wrong image name being uploaded.

Fix typo in push.yml for testing image

---

util/cpeutils.c
util/cpeutils.h
util/cpeutils_tests.c

Implemented (speed) optimizations for the new CPE matching in CVE scans.
An improvement of the performance seemed necessary.
GEA-626

Implemented optimizations for the new CPE matching in CVE scans.

---

util/compressutils.c
util/compressutils.h
util/compressutils_tests.c

Added a function that opens a gzip file for reading via a file descriptor.
This is used for loading some compressed feed files in gvmd.
GEA-635

Add: Added a function that opens a gzip file for reading via a file descriptor.

---

INSTALL.md

Fix link to Cgreen install.
Was outdated.

Fix: Cgreen link

---

util/CMakeLists.txt
util/kb_tests.c

Add kb_tests.c.
Start of test coverage for kb.c.

Add: first tests of kb.c

---

.gersemirc
.github/workflows/ci-c.yml
CMakeLists.txt
README.md
base/CMakeLists.txt
boreas/CMakeLists.txt
cmake/MacroAddUnitTest.cmake
cmake/MacroGitGetRevision.cmake
doc/CMakeLists.txt
gmp/CMakeLists.txt
http/CMakeLists.txt
openvasd/CMakeLists.txt
osp/CMakeLists.txt
tests/CMakeLists.txt
util/CMakeLists.txt

Add a GitHub workflow that checks the format of the CMake files and shows a diff of the necessary changes.
The workflow uses a new tool called [gersemi](https://github.com/BlankSpruce/gersemi) that is used to format the code automatically and also to check if the changes in a PR need reformatting. The README contains a new section on how to install the tool.
Not having to comment on CMake indentation and code formatting in PRs.
https://jira.greenbone.net/browse/GEA-909

Add workflow for checking the CMake file format

---

base/CMakeLists.txt
base/credentials_tests.c

Add tests of `base/credentials.c`.
Increasing coverage.

Add: tests of base/credentials

---

.github/workflows/ci-c.yml
CMakeLists.txt
http_scanner/CMakeLists.txt
http_scanner/http_scanner.c
http_scanner/http_scanner.h
http_scanner/http_scanner_test.c
http_scanner/libgvm_http_scanner.pc.in
openvasd/openvasd.c
openvasd/openvasd.h
openvasd/openvasd_tests.c

Extract a generic HTTP scanner library
The generic library can be reused for different scanner types
GEA-1230

Change: Extract a generic HTTP scanner library

---

http/httputils.c
http/httputils.h
http_scanner/http_scanner.c
http_scanner/http_scanner.h
openvasd/openvasd.c

Refactor code and header inclusion (curl.h) to avoid build issues.
Move some functionality from `openvasd` to `http_scanner` and `httputils`
Fix build issues
GEA-1230

Change: Code refactoring to fix build issues

---

http_scanner/http_scanner.c
util/vtparser.c

Improve error handling when parsing tags for VTs and return an error on missing severity
Improve error handling

Change: Improve error handling when parsing VTs

---

CMakeLists.txt
container_image_scanner/CMakeLists.txt
container_image_scanner/container_image_scanner.c
container_image_scanner/container_image_scanner.h
container_image_scanner/container_image_scanner_tests.c
container_image_scanner/libgvm_container_image_scanner.pc.in

Add support to build the JSON object to start container image scanning tasks
To support container image scanning
GEA-1254

Add: Starting container image scanner tasks

---

util/versionutils.c
util/versionutils_tests.c

Fix two errors in `cmp_versions`.
Certain version checks were failing.

Fix: a couple cases in cmp_versions

---

base/CMakeLists.txt
base/strings_tests.c

Add tests of `strings.c`.
Increases coverage.

Add: tests of base/strings.c

---

base/CMakeLists.txt
base/prefs_tests.c

Add tests of `base/prefs.c`.
Improve coverage. Help to show leaks.

Add: tests of base/prefs.c
