base/hosts.c
base/networking.c
base/networking.h

This will result in multiple target hosts, one for each IP, and with the
initial hostname added to the host's vhosts list, instead of only
considering the first returned IP as before.

Handle hostnames that resolve to multiple IPs.

---

util/kb.c
util/kb.h
util/nvticache.c

Use Redis lists to store NVT's metadata, instead of a separate sets with
repeated value names, for each information. Reduces Redis memory footprint
(~120M vs ~276M) and fresh load-up speed (~40sec vs ~52sec)
$ time openvassd -C
real	0m52.348s
user	0m35.108s
sys	0m8.008s
redis /tmp/redis.sock[1]> info memory
Memory
used_memory:290317280
used_memory_human:276.87M
used_memory_rss:302620672
used_memory_rss_human:288.60M
$ time openvassd -C
real	0m40.362s
user	0m31.848s
sys	0m4.116s
redis /tmp/redis.sock[1]> info memory
Memory
used_memory:125899440
used_memory_human:120.07M
used_memory_rss:133787648
used_memory_rss_human:127.59M

Reduce nvticache memory footprint in Redis.

---

base/nvti.c

This ensures that the contents of the README.md are displayed in the Introduction section in the Doxygen-generated overview page like before.

Update file name for Doxygen Introduction file as well

---

nasl/exec.c

Fix regression introduced in r29164. Don't call cell2str() before
cell2atom() as it leads to executing expressions such as incrementations
and function calls twice.

Backport r30032.

---

base/prefs.c

Check if hash table is actually non-NULL before trying to use
g_hash_table_iter_init () to avoid segmentation fault.

Do not try to initialize iterator for non-existent hash table

---

misc/plugutils.c

Unlike on trunk, nvti_free() is already called, so don't free plugin
name.

Fix backport of r30042.

---

ChangeLog
misc/plugutils.c

* misc/plugutils.c (get_plugin_preference): When no value is found in
memory preferences, use the default one from nvticache.

Backport misc/ part of r29656.

---

nasl/nasl_grammar.y

Only verify the signature of sha256sums (or md5sums) file, and use the checksums in it to verify the nasl/inc files, instead of verifying the signature of each one of them.

Backport signature verification changes

---

util/nvticache.c
util/nvticache.h

util/nvticache.c (nvticache_free): Set src_path pointer to NULL.
util/nvticache.h: Remove double entry.

util/nvticache.c (nvticache_free): Set src_path pointer to NULL.

---

base/nvticache.c
base/nvticache.h

Remove nvticache_free().
Do the cleanup on nvticache_init() call. Do not delete the cache kb
content.

Backport PR #29.

---

nasl/nasl_grammar.y

Use kb_item_set_str() to insert checksum.
This ensures that we don't get duplicate checksum values in the kb,
leading to occasional errors during checksum errors.

Backport scanner PR #22.

---

util/kb.c
util/nvticache.c
util/nvticache.h

So that an nvtcache from openvas-9 isn't wrongly used. Also store the
feed version in that key.

Use "nvticache10" value to identify cache KB.

---

nasl/nasl_socket.c

With adjustments due to code change
Check for the scanner option "time_between_request". This option avoid quick
connection establishment, termination and quick request to a single host.
* nasl/nasl_socket.c: Include gvm/base/prefs.h, stdlib.h and sys/time.h.
(wait_before_next_probe): New function.
(nasl_open_privileged_socket, nasl_open_sock_tcp_bufsz, nasl_send,
nasl_close_socket): Call new function

Backport part of PR #24 (openvas-scanner).

---

CMakeLists.txt
INSTALL

Previously CMake only checked for the presence of libgcrypt, causing
build failures when the installed libgcrypt was too old and did not
provide the required symbols.
This commit adds a version check for libgcrypt which will fail if the
version is below 1.6. This version requirement is now documented in the
INSTALL file as well.

Fix #40: Check the version of libgcrypt

---

nasl/nasl.h
nasl/nasl_grammar.y

Save parsed tree cells of included files for later re-usage. Reduces load-up time from ~3m30 to ~55s.

Backport r28888 and openvas-scanner PR #36.

---

util/kb.c

Use nvticache_required_ports() instead of nvticache_required_keys().

Fix value inserted in nvticache.

---

base/kb_redis.c

Fix value inserted in nvticache.
Use nvticache_required_ports() instead of nvticache_required_keys().

Backport PR #46.

---

nasl/nasl_scanner_glue.c

Enable specifying a regex-based mandatory key.
When using script_mandatory_keys("foo", re:"bar=someregex"), the
mandatory key "bar" must be present in the KB, and contain a value that
matches the regex. Matching behaviour is case insensitive, like the nasl
'~' operator. eg. Faar is a valid value for fa*r.

Backport parts of scanner PR #34.

---

gmp/libgvm_gmp.pc.in
osp/libgvm_osp.pc.in
util/fileutils.c

* gmp/libgvm_gmp.pc.in: Update requirement from 2.32 to 2.42.
* osp/libgvm_osp.pc.in: Update requirement from 2.32 to 2.42.
* util/fileutils.c (gvm_file_move, gvm_file_copy ): Drop check for glib
older 2.36 since we have minimum 2.42. Drop the respective deprecated code.

Update remains to minimum glib verison 2.42.

---

CMakeLists.txt

GHmac and its functions are used in nasl/nasl_crypto.c. They got
introduced in glib with version 2.30 (see
https://developer.gnome.org/glib/stable/glib-Data-HMACs.html for details).
Therefore update the minimum required glib version.

Require glib>=2.30 for GHmac

---

base/logging.c
base/networking.c
base/pwpolicy.c
doc/Doxyfile_full.in
osp/osp.c
util/authutils.c
util/kb.c
util/nvticache.c
util/serverutils.c

Add missing documentation to undocumented functions corresponding to
gvm_base and gvm_util libraries.
Add gmp and osp as path in doc/Doxyfile_full.in to generate the
corresponding documentation for gvm_osp and gvm_gmp libraries, since
before it was not  generated.

Add doc-strings to functions.

---

gmp/gmp.c
gmp/gmp.h

Almost all function had been already renamed with the gmp_ prefix.
Only two were still without the prefix and were renamed (unknown reason).
Other modules (gvm, gvm-tools, openvas-cli, gsa) were checked and no 
one call the renamed functions.
* gmp/gmp.c (gmp_check_response, gmp_check_response_c): Rename function.
It was before check_response and check_response_c respectively.
Other functions use the new names to call them.
* gmp/gmp.h (check_response): Remove prototype.

Remove old TODO.

---

gmp/gmp.c

gmp_check_response() takes a new argument entity_t type to allow the used of this function for another ones which needs to retrieve the entity.
All functions which already call gmp_check_response() has been updated appropriately.

Resolve TODO

---

CMakeLists.txt

When working with a pull request the git revision returned by the
command `git rev-parse --abbrev-ref HEAD` will return something like
`pull/1234` as the branch name.
Using revision strings containing slashes result in build failures since
the string is used for the `.so` files, leading to file names ending
ending in `~git-1a2b3c4-pull/1234` passed as output files to the linker
which interprets the slash as a separator and attempts to write to a
non-existent directory.
This commit replaces any slashes with underscores, resulting in a suffix
like `pull_1234` instead.

Escape slashes in git revision

---

.circleci/config.yml

This PR updates the location of the Docker image used in the CI environment and adds two new build jobs.
1. A job for performing static analysis using `scan-build` (`ccc-analyzer`) and collecting the resulting report as a build artifact
1. A job for determining the coverage of the source code documentation using `doxygen` and `doxy-coverage`
Note that both jobs are currently mainly informational, i.e. issues found by scan-build will not cause the build to fail and decreasing documentation coverage will also be permitted as long as it stays above 80%. This can (and likely will) be changed easily in the future so that scan-build issues and drops in documentation coverage trigger a CI failure to be reported in GitHub.

Improvements for CI workflow

---

CMakeLists.txt

This commit adds a new CMake option called `ENABLE_COVERAGE`. When
activated, this option will cause the `--coverage` option to passed to
the C compiler. This option is used to compile and link code
instrumented for coverage analysis.
Running code built with `--coverage` will result is coverage data and
notes being recorded and stored in the build directory. The recorded
data can then be consumed by `gcov` and related tools.
The `ENABLE_COVERAGE` option is only supported for the `Debug` build
type as compiler optimizations performed for other build types would
render the coverage measurements less meaningful.

Add option to enable support for coverage analysis

---

base/hosts.c

Solve ccc-analyzer warning: "Access to field 'vhosts' results in a
dereference of a null pointer (loaded from variable 'removed')"

* base/hosts.c (gvm_hosts_deduplicate): Check for null pointer.

---

util/kb.c

Check if kbr->max_db is initialized. If not, it calls fetch_max_db_index() to initialize kbr->max_db and search in all DBs.

* utils/kb.c (redis_find): Call fetch_max_db_index().

---

doc/Doxyfile.in
doc/Doxyfile_full.in
doc/Doxyfile_xml.in

This commit make the `INPUT` of all `Doxyfile`s consistent. This enables
the generation of documentation for the subdirectories `gmp` and `osp`
which was previously only done for the `full` flavor.

Generate documentation for all subdirectories

---

.circleci/config.yml

This commit extends the step for establishing the documentation coverage
by adding support for submitting the coverage data to `codecov.io`.
The step now use `coverxygen` instead of `doxy-coverage` which is able
to generate coverage data close to the format expected by `lcov` and
usable by `codecov.io`.

Submit documentation coverage information to codecov

---

README.md

This commit adds a badge generated by `codecov.io` indicating the
current coverage of the source code documentation.

Add documentation coverage badge

---

.circleci/config.yml

This commit removes the CI step for fixing the negative coverage counts
emitted by coverxygen as this fixed in versions >= 1.3.1 (see psycofdj/coverxygen#7).

Remove fix for negative coverage counts

---

README.md

This commit adds text right next to the documentation coverage badge to
make it clear that this badge refers to the documentation coverage and
changes the placement of the badge for consistence with other modules.

Explain documentation coverage badge

---

util/kb.c
util/kb.h
util/nvticache.c

-  Add kb_nvt_get_oids().
-  Store NVT timestamp and OID in a single list key.

Nvticache filenames

---

misc/radius.c

￼￼
Backport PR #109
Add preprocessor directives to select the radius client dictionary path.

Backport PR #109

---

misc/radius.c

Embedded creation of Radius client configs is broken in the versions of
radcli currently packaged by Debian, so as a workaround create the
config using a temp file when using radcli.

Create Radius config from file when using radcli

---

CMakeLists.txt

Backport of scanner PR https://github.com/greenbone/openvas-scanner/pull/165 to the openvas-libraries-9.0 branch.

[9.0] Correct name for netsnmp lib

---

util/CMakeLists.txt
util/nvticache.h

Use the gvm-libs release version in the name of the nvticache.

Add definition for NVTICACHE_STR.

---

base/prefs.c

For preferences that are used by both openvas-nasl and openvassd.
Instead of having extra checks/insertions for openvas-nasl, like in https://github.com/greenbone/openvas-scanner/pull/188

Set default preferences values in prefs_init().

---

base/hosts.c
base/logging.c
doc/Doxyfile.in
doc/Doxyfile_full.in
doc/Doxyfile_xml.in
util/authutils.c
util/kb.c
util/kb.h
util/xmlutils.c

Fix various typos found by [codespell](https://github.com/codespell-project/codespell) 1.14
```
codespell . -S ".git,build" | grep -v "therefor"
```
(For some words the -S parameter doesn't work correctly)

Fix various typos.

---

misc/network.c
misc/network.h
nasl/nasl_init.c
nasl/nasl_socket.c
nasl/nasl_socket.h
nasl/tests/test_socket.nasl

Remove NASL get_ssl_compression().
Support for compression was removed in TLS 1.3 and GnuTLS 3.6. The
related GnuTLS functions were deprecated. Also this NASL function was
never used.
Issue: https://github.com/greenbone/gvm-libs/issues/63

Backport scanner PR #204.

---

INSTALL.md
README.md

The commits adjust layout and content of the `README` file to match the template provided by the `greenbone/templates` repository. Also, the `INSTALL` file format is switched to Markdown, with an update of relevant sections.

Rework README to match template

---

misc/network.c

Backport of https://github.com/greenbone/openvas-scanner/pull/207 and https://github.com/greenbone/openvas-scanner/pull/205 to the openvas-libraries-9.0 branch.
See also https://github.com/greenbone/openvas-scanner/issues/206

[9.0] Enable GnuTLS RC4 and/or COMPAT

---

base/nvticache.c

Check for NULL before passing category to atoi().

---

nasl/nasl_isotime.c

Warning is erroneous, as the number of printed bytes is limited. Check
snprintf() return value to silence it.
without the
`*timebuf = '\0';`
The compiler optimizes-out the if() check.
Fixes #143

Fix format-truncation warning in GCC 8.2.

---

util/kb.c

This ensures ordering of a key's inserted values, and removes unicity of
values for a key.
PR can't be merged at the moment, as many VTs out there still rely on the unicity "feature/bug"
Related post from 2014, on usage of unordered sets instead of lists: https://marc.info/?l=openvas-development&m=139326215027633&w=2

Switch KB from using unsorted sets to lists.

---

util/kb.c

Instead of first one, in order to make behaviour more consistent.

redis_get_single() returns key's last value.

---

README.md

This way we can have a more clear description that this is actually the documentation coverage and not code test coverage.
Remove the text, that clarifies that before, but looks sloppy.

Use shields.io badge for doc coverage

---

util/authutils.c

This is done to avoid trying to initialize the memory pool twice.

Check if gcrypt is init'ed in gvm_auth_init

---

misc/openvas_auth.c

This is done to avoid trying to initialize the memory pool twice.

Check if gcrypt is init'ed in openvas_auth_init (9.0)

---

util/fileutils.c

This adds new placeholders in `gvm_export_file_name` for day, month and year of the modification date and makes it replace ASCII whitespace and control characters with underscores.

New filename placeholders

---

base/openvas_file.c

This adds new placeholders in `openvas_export_file_name` for day, month and year of the modification date and makes it replace ASCII whitespace and control characters with underscores.

New filename placeholders 9.0

---

misc/prefs.c

Fix lost of path to config file.
After sending -SIGHUP to the scanner to force a reload,
the path to the config file was overwritten. Now the configurations
in the config file are preserved.
Backport of https://github.com/greenbone/gvm-libs/pull/167

Backport greenbone/gvm-libs#167

---

util/authutils.c
util/authutils.h

It was an empty function with a reference to a list to be freed, which was removed
in 2015. So, nothing to be freed. There is no plan to extend it. Therefore remove it.

Solve TODO. Remove gvm_auth_tear_down().

---

base/hosts.c
gmp/gmp.c
osp/osp.c
util/kb.c
util/serverutils.c

These caused warnings during documentation builds.

Fix missing and erroneous doc parameters.

---

util/kb.c

In order to not have duplicate or removed values in the nvticache.

Delete old preferences before inserting new ones.

---

base/hosts.c

Prior implementation used an O(N^2) routine. This one has O(N) time complexity.
With a /8 network, the routine takes a couple of seconds, instead of multiple hours.

Rework gvm_hosts_shuffle() implementation.

---

base/openvas_hosts.c

Prior implementation used an O(N^2) routine. This one has O(N) time complexity.
With a /8 network, the routine takes a couple of seconds, instead of multiple hours.
Backport of https://github.com/greenbone/gvm-libs/pull/199

Rework openvas_hosts_shuffle() implementation.

---

base/hosts.c

Performance fixes related to handling large sets of hosts.
Backport of https://github.com/greenbone/gvm-libs/pull/202

Backport #202

---

base/openvas_hosts.c
base/openvas_hosts.h

Performance fixes related to handling large sets of hosts.
Backport parts of https://github.com/greenbone/gvm-libs/pull/202

Backport parts of #202

---

base/hosts.c

As gvm_hosts_deduplicate() is now only called when there are new entries
added to the hosts list.

Reset hosts iterator at the end of gvm_hosts_resolve().

---

base/hosts.c

Reset hosts iterator at the end of gvm_hosts_resolve(). 
As gvm_hosts_deduplicate() is now only called when there are new entries
added to the hosts list.
Backport of https://github.com/greenbone/gvm-libs/pull/205

Backport PR #205

---

base/hosts.c
base/hosts.h

Use a dynamic array for gvm_hosts instead of doubly-linked lists.
This substantially improves handling of large sets of hosts.
ie. With a "10.0.0.0/8" hosts string, memory footprint is reduced from
1.33GB to 0.9GB. Other operations times such as creation and shuffling
are also slightly faster.

Reduce memory footprint when handling large hosts sets

---

base/hosts.c
base/hosts.h

Use a dynamic array for gvm_hosts instead of doubly-linked lists.
This substantially improves handling of large sets of hosts.
ie. With a "10.0.0.0/8" hosts string, memory footprint is reduced from
1.33GB to 0.9GB. Other operations times such as creation and shuffling
are also slightly faster.
Backport of https://github.com/greenbone/gvm-libs/pull/207

Backport PR #207

---

util/kb.c

Close connection if the key was not found, before continuing search in the next kb.
This avoid the "Too many open files" issue.

Fix redis_find(). 

---

util/kb.c

Close connection if the key was not found, before continuing search in the next kb.
This avoid the "Too many open files" issue.

Backport PR #215

---

base/hosts.c

Also ignore case when comparing hostnames.

Always add hostnames and vhosts in lower-case format.

---

util/nvticache.c

Plugin feed version file: Show message only once if it is not found.
Backport PR #219

Backport PR #219

---

util/kb.c

Use g_log instead of g_debug for No redis DB available message.
Backport PR #223

Backport PR #223

---

base/hosts.c

As a hostname entry is removed from the array, even if it didn't resolve
to an IP address.
Also don't decrement hosts count inside the loop.

Always fill gaps in gvm_hosts_resolve().

---

base/hosts.c

Backport of  https://github.com/greenbone/gvm-libs/pull/227 and parts of https://github.com/greenbone/gvm-libs/pull/211

Backport fixes to gvm_hosts_resolve().

---

util/kb.c
util/kb.h

It is up to the caller to retry if needed. Otherwise, it is possible to be stuck in sleep & retry loops waiting for DB slots.

Remove inconsistent delays in kb routines.

---

base/nvti.c
base/nvti.h
util/kb.c

These changes reflect the unified handling of cross references in the NVT meta data
in the C-libraries, primarily the structure and API around nvti_t.
Essentially a new structure vt_ref_t is introduces, a list of references owned by a nvti_t.
The explicit storage of references as strings is removed from nvti_t.
The API for handling references is reduced to generic functions like nvti_refs(), nvti_add_ref() and nvti_add_refs() that are applicable to any type of reference. All previous API elements to handle cve, bid, xref were removed.
nvt_refs() and nvti_add_refs() are pretty powerful to handle various ways to get/add lists of references. This reflects the two ways how references were used before: cve and bid as simple lists and xref as type-including syntax.
This patch corresponds with …

New xrefs data model

---

base/nvti.c
base/nvti.h

This function was missing. Now the API is complete for vtref.

Add function vtref_text().

---

util/gpgmeutils.c
util/gpgmeutils.h

The S/MIME email encryption will now accept the more common PEM X.509
certificate format in addition to PEM-encoded PKCS#7.
For this the new function gvm_gpg_import_many_types_from_string has been
added, which is also used internally in gvm_gpg_import_from_string and
when importing the certificates.

Allow multiple certificate formats for S/MIME (10.0)

---

util/gpgmeutils.c
util/gpgmeutils.h

(Port of #231 to master branch)
The S/MIME email encryption will now accept the more common PEM X.509
certificate format in addition to PEM-encoded PKCS#7.
For this the new function gvm_gpg_import_many_types_from_string has been
added, which is also used internally in gvm_gpg_import_from_string and
when importing the certificates.

 Allow multiple certificate formats for S/MIME (master)

---

osp/osp.c
osp/osp.h

This adds various functions and types for starting a scan with extended
options like a list of VTs and targets with credentials.

Add functions, types for extended OSP start_scan

---

base/nvti.c

There might be situations where ref_ids is NULL,
so return an error instead of handing it over to g_strsplit()
which will bail out via assert().

Prevent g_strsplit to be called with NULL.

---

CHANGELOG.md
CHANGES-OLD

The format is based on Keep a Changelog (https://keepachangelog.com/en/1.0.0/).
Move the old CHANGES file with the release changes summary for gvm-libs versions before 10.0.0 to CHANGES-OLD. This file was updated also with the last missing changes for gvm-libs-1.0

Create CHANGELOG.md with new format.

---

util/kb.c
util/kb.h

Remove inconsistent delays in kb routines.
It is up to the caller to retry if needed. Otherwise, it is possible to be stuck in sleep & retry loops waiting for DB slots.
Original PR #230 from Hani.

Backport PR #230

---

osp/osp.c

The caller may have passed an empty opt.scanner_params.

Add init and check in osp_start_scan_ext

---

base/nvti.c
base/nvti.h

This makes it unnecessary to handle the QoD Type in the "tags" parts.
If it is added to the tags, it still will be. This is how openvas uses it.
The change is intended to support gvmd so it can use this new API element
and prevent qod_type to enter the tags element.

Make QoD Type an explicit element of stuct nvti.

---

osp/osp.c
osp/osp.h

In contrast to function get_vts(), this function allows to
call GET_VTS with the "filters" parameter.

Add function osp_get_vts_filtered().

---

util/kb.c

The nvti struct elements should not be accessed directly.
This patch takes fixes the last occurance in gvm-libs of direct
access.

Use API to access nvti information.

---

base/nvti.c
base/nvti.h

This enforces to use the intended API. It
can not be bypassed anymore by accessing the elements directly.

Make the actual nvti struct internal.

---

INSTALL.md

`libldap2` is a prerequisite library, but it's not listed in the `apt-get` section. This causes the library to compile without LDAP support.
I also reindented the `apt-get` command to list one library per line, for clarity. This makes explicit that there is not a 1-to-1 correspondence between the prerequisites and the `apt-get` command. For instance, `libgio` is not explicitly included. Since adding `libldap2-dev` fixed my issues I haven't investigated that further, but an expert might want to take a closer look.

Add libldap2-dev to prerequisites

---

base/nvti.c
base/nvti.h

This means to add explicit methods to set and get solution and solution_type.

Make solution and solution_type explicit for nvti

---

CHANGELOG.md
CMakeLists.txt
util/kb.h

Add a new CMake directive (-DREDIS_SOCKET_PATH=/path/to/socket)to allow
to set the path to the redis unix socket at build time.
Additionally change the default path to use the default socket path of
redis on debian and ubuntu which is (/var)/run/redis/redis.sock.

Allow to configure the path to the redis socket

---

base/nvti.c
base/nvti.h

This makes "summary", "insight", "affected", "impact" and "detection"
explicit elements of the nvti struct. Including the functions
to get and set them.

Add explicit attributes in nvti struct

---

base/nvti.c
base/nvti.h
util/nvticache.c

This makes the internal structure of nvtpref_t
invisible to functions using it. Using the official
API is enforced.

Internalize struct nvtpref_t

---

CHANGELOG.md
osp/osp.c
osp/osp.h

Related to PR greenbone/ospd#131

Add osp_get_performance()

---

CHANGELOG.md
base/nvti.c
base/nvti.h

So far it was only possible to set the entire tags
string. Now it is possible to append a single tag.

Add nvti_add_tag() for adding a single tag to tags.

---

CHANGELOG.md
base/nvti.c

OSP should only use seconds since epoch for timestamps to provide
the OSP clients with a reliable format/syntax.
This patch transforms incoming timestamps immediately.
The OpenVAS-specific parsing code for timestamp is moved here and can
later be remove from gvmd where it currently is used to parse the various
syntax's.
A positive side effect is the reduced size consumption in redis:
The string "2019-05-14 08:13:05 +0000 (Tue, 14 May 2019)"
becomes "1557821585"

Convert incoming timestamp tags to seconds since epoch

---

CHANGELOG.md
base/nvti.c

When a NASL script sets the tag "cvss_base" it will not be added
to the tags for the respective NVT anymore. Thus it will also not
be stored anymore in the redis database.
This saves some space and, when tags are parsed, computing time.
Not a fundamental improvement though.
The OSP protocol already ignores this tag because the value
can be computed from the vector anyway.
So, this does not require other changes.

Ignore redundant tag cvss_base.

---

CHANGELOG.md
osp/osp.c

It checks that titles exists and it is not a null string.
Also, it checks that start and end params are a valid epoch time value.

Check for opts params in osp_get_performance_ext()

---

CHANGELOG.md
util/nvticache.c

Check for null before trying to save the value in Redis.
Fix and close Issue greenbone/openvas#406
Also, fix typo in changelog as in PR #278

[11.0] Fix sigsegv when no plugin_feed_info.inc file present.

---

CHANGELOG.md
util/nvticache.c

Check for null before trying to save the value in Redis.

Fix sigsegv when no plugin_feed_info.inc file present.

---

base/CMakeLists.txt
base/nvti.c
base/nvti_tests.c

This makes the nvtis code allocate strings for the keys of nvtis_t hashtables, instead of reusing the nvt->oid pointers as keys.
The problem with reusing the nvt->oid pointer is that any call to nvt_set_oid will free that pointer.
I don't think this affects any of our current code because we always call nvt_set_oid only once.  But this caught me out during my first attempt at greenbone/gvmd/pull/826, and I had to spend too much time debugging that.

Use dedicated memory for nvtis keys

---

CHANGELOG.md
CMakeLists.txt

The binary test-host is more of a tool than a test.  It only has one
fail case, but this failure is not possible with the way it is called in
testhosts.

Disable testhosts test as it's not really a test

---

CHANGELOG.md
util/CMakeLists.txt

[11.0] Fix missing linking to libgnutls in util/CMakeLists.txt

---

base/nvti.c

Function g_free() test for NULL prior to free'ing the memory.
So the extra conditional is not needed.

Remove unneeded NULL check.

---

base/nvti.c
base/pidfile.c
osp/osp.c
util/authutils.c
util/fileutils.c
util/gpgmeutils.c
util/radiusutils.c
util/serverutils.c
util/uuidutils.c
util/xmlutils.c

We were mixing `__func__` and `__FUNCTION__`, so we're switching all to `__func__`.
GCC manual: `__FUNCTION__` is another name for `__func__`, provided for backward compatibility with old versions of GCC.

Replace __FUNCTION__ with __func__

---

CHANGELOG.md
base/nvti.c
base/nvti.h
base/nvti_tests.c

The solution method is handled analog to the solution type
and allows for a more refined formal solution definition.

Add solution method to nvti.

---

CHANGELOG.md
CMakeLists.txt
base/CMakeLists.txt
util/CMakeLists.txt
util/xmlutils.c
util/xmlutils.h
util/xmlutils_tests.c

Add a fast memory-only XML parser (9.0)

---

.circleci/config.yml
CHANGELOG.md
CMakeLists.txt
base/CMakeLists.txt
base/version.c
base/version.h
base/version_tests.c
util/CMakeLists.txt

Allow users of gvm-libs request the current version string.
**Checklist**:

Add a gvm_libs_version function

---

CHANGELOG.md
util/xmlutils.c

This speeds up read_string_c by skipping the creation of the unused entity_t, which also reduces the amount of memory used.
**Checklist**:

Don't create an entity tree during read_string_c (11.0)

---

CHANGELOG.md
util/gpgmeutils.c

The certificates used for S/MIME encryption are now added to the GPG
trust list automatically because users cannot always confirm trust.
Also, a data buffer with custom I/O functions is used to write the
encrypted data because gpgme_data_new_from_stream can cause problems
when trying to write afterwards.
**Checklist**:
- Tests N/A

Fix trust and file handling for S/MIME (11.0)

---

util/gpgmeutils.c

The certificates used for S/MIME encryption are now added to the GPG
trust list automatically because users cannot always confirm trust.
Also, a data buffer with custom I/O functions is used to write the
encrypted data because gpgme_data_new_from_stream can cause problems
when trying to write afterwards.
**Checklist**:
- Tests N/A

Fix trust and file handling for S/MIME (10.0)

---

CHANGELOG.md
gmp/gmp.c

To ensure the previous behavior of getting the results etc. the details
attribute has been added to the sent GMP command.
**Checklist**:
- [] Tests N/A

Get details with get_reports in gmp_get_report_ext (11.0)

---

CHANGELOG.md
gmp/gmp.c
util/gpgmeutils.c
util/kb.c
util/nvticache.c
util/serverutils.c
util/xmlutils.c

This merges changes from #305, #308, #309, #311 and #313 into the master branch.
**Checklist**:
- Tests N/A

Merge gvm-libs-11.0 into master

---

CHANGELOG.md
util/xmlutils.c

For exporting a XML report in gsad the `print_entity_to_string` function
is used. While reading the report entity from the response all XML
entities are unescaped. Therefore when using the
`print_entity_to_string` it may create invalid XML attributes. Therefore
ensure that all invalid characters for attributes (like &) are escaped
before writing the entity to the GString.

Fix printing valid xml attributes for an entity

---

CHANGELOG.md
base/hosts.c
base/hosts.h

Add function for getting a gvm_host_t by string. This is used in the test_alive_hosts_only feature of openvas.
Related PR:
- [openvas](https://github.com/greenbone/openvas/pull/456)
- [ospd-openvas](https://github.com/greenbone/ospd-openvas/pull/204)

get new gvm_host_t by string

---

CHANGELOG.md
base/hosts.c

The pointer p points to a part in block_str, and block_str points to
addr_str. So, the addr_str must be g_free()'d after check p.

Fix is_cidr_block().

---

CHANGELOG.md
gmp/gmp.c
gmp/gmp.h

This is an extensible replacement for gmp_start_task_report_c, with an
additional return value to indicate that permission was denied.
**Checklist**:

Add gmp_start_task_ext_c

---

CHANGELOG.md
base/logging.c
base/logging.h

Also, update version in Changelog

Make log mutex visible

---

CHANGELOG.md
CMakeLists.txt

This cleans up and updates the Changelog and CMake files for the coming 11.0.2 release.
**Checklist**:
- Tests N/A

Prepare 11.0.2 release

---

CHANGES
CMakeLists.txt

This cleans up and updates the Changelog and CMake files for the coming 10.0.2 release.
**Checklist**:
- Tests N/A

Prepare 10.0.2 release

---

CHANGELOG.md
CMakeLists.txt

This changes the version number to 11.0.1
**Checklist**:
- Tests N/A

Prepare 11.0.1 release

---

CHANGELOG.md
osp/osp.c
osp/osp.h

Add new scan status PENDING.

---

CHANGELOG.md
CMakeLists.txt
base/CMakeLists.txt
base/hosts.c
base/hosts_tests.c

[11.0] Fix is_cidr6_block() and is_short_range_network()

---

CHANGELOG.md
base/CMakeLists.txt
base/networking.c
base/networking.h
base/networking_tests.c

Add implementation for getting the interface which is used for routing to a given destination. If provided a source address is set to the address of the interface to use.

Get interface used for routing to given destination

---

CHANGELOG.md
util/gpgmeutils.c

This fixes an issue where iterating over the key list could get stuck
in a loop and after fetching the key for the email address.
Also, more GPGME calls are now checked for errors.
**Checklist**:
- Tests N/A

Fix S/MIME keylist and improve error handling (master)

---

CHANGELOG.md
util/gpgmeutils.c

This fixes an issue where iterating over the key list could get stuck
in a loop and after fetching the key for the email address.
Also, more GPGME calls are now checked for errors.
**Checklist**:
- Tests N/A

Fix S/MIME keylist and improve error handling (11.0)

---

CHANGES
util/gpgmeutils.c

This fixes an issue where iterating over the key list could get stuck
in a loop and after fetching the key for the email address.
Also, more GPGME calls are now checked for errors.
**Checklist**:
- Tests N/A

Fix S/MIME keylist and improve error handling (10.0)

---

CHANGELOG.md
osp/osp.c
osp/osp.h

Because the parallel option for multitarget task is deprecated in OSP

Remove parallel from target options

---

boreas/alivedetection.c
boreas/alivedetection.h
boreas/boreas_io.c

Remove max_alive_hosts scan restriction as it is currently not planned to be used and makes the code more complex.
**Checklist**:

Simplify scan restrictions

---

CHANGELOG.md
osp/osp.c
osp/osp.h

As get_vts OSP command was extended with a new attribute version_only,
the function use get_vts with this attribute instead of the get_version command,
because now all wrappers have a vts collection and therefore, not always
get_version response has a vts entity.

Modify osp_get_vts_version()

---

boreas/alivedetection.c
boreas/ping.c

Only ping a host once if it is alive.
Hosts may still be pinged twice If the list of target hosts is short and the pinged host takes longer than the specified timeout to reply.
**Checklist**:

Ping host only once if alive

---

boreas/alivedetection.c

The hosts need to be put on the alive hosts list for Consider Alive too. This is needed for calculating the correct amount of dead hosts for the calculation of the progress bar.
**Checklist**:

Add host to alive hosts list for Consider Alive

---

boreas/alivedetection.c

This way we not only allow the predefined
alive test combinations as used in ping_host.nasl
but all possible combinations. The predefined
combinations work roughly the same as before.
Only the order of methods may change.
Order is icmp -> tcp-syn -> tcp-ack -> arp now.
**Checklist**:

Allow all alive test combinations

---

CHANGELOG.md
boreas/alivedetection.c
boreas/boreas_io.c
boreas/boreas_io.h
boreas/cli.c

When we reach the max_scan_hosts limit we do not need send the true number of dead hosts.
The number needed by ospd-opevas for calculating the correct progress bar and not ending a scan in the interrupted state is calculated by subtracting the number of max_scan_hosts and alive hosts from the number of target hosts.
**Checklist**:

Send the correct num of dead hosts to ospd-openvas

---

CHANGELOG.md
base/hosts.c
base/hosts.h

Also add a function to access this variable directly.

Separate duplicated hosts from removed hosts in the hosts structure.

---

CHANGELOG.md
boreas/alivedetection.c
boreas/alivedetection.h
boreas/sniffer.c

**What**:
Continuously send new dead hosts to ospd-openvas to gradually update the progress bar for the case that only ICMP was chosen as alive test.
**Why**:
To get a better user experience when looking at the progress bar for the most common case of ICMP ping.
**How**:
Tested with scans via gvm-cli and looked if the count of dead hosts which are send to ospd-openvas are correct. 
* Few hosts in target list and many hosts in target list
* max_scan_hosts set and not set
* max_scan_hosts reached in last batch of packet and in previous batch of packets.
**Checklist**:

Smooth progress icmp

---

CHANGELOG.md
boreas/alivedetection.c
boreas/util.c

**What**:
Fix type conversion bug. Because of this bug it could happen that not all ports are added correctly to the port list for TCP pings.
If we init an GArray with elements of type int and then get elements from this array with g_array_index (array, uint16_t, index) we get 0 every second port. This is fixed by always using uint16_t when initing the array and when filling it.
**Why**:
Bugs have to be fixed.
**How**:
Printed out the array of ports after it got filled. Before fix every second port was 0, after fix all ports are filled as expected.
**Checklist**:

Use correct type size for port elements

---

CHANGELOG.md
boreas/alivedetection.c
boreas/boreas_io.c
boreas/boreas_io.h
util/gpgmeutils.c

**What**:
The related PRs make it possible to supply a dedicated port list for alive detection via OSP. This PR enabled the usage of this port list.
Depends on:
https://github.com/greenbone/ospd/pull/323
https://github.com/greenbone/ospd-openvas/pull/327
**Why**:
It enhances the flexibility when doing alive scans.
**How**:
Used gvm-cli for scans. Added <alive_test_ports>22,80<alive_test_ports> and checked with a print if these ports were actually used. 
**Checklist**:

Use dedicated port lists for alive detection if supplied

---

CHANGELOG.md
util/xmlutils.c

**What**:
Retry if xml response via tls1.3 is still not received.
This is done only for those cases in which a timeout is not set.
**Why**:
For some reason, TLS1.3 behaves different than TLS1.2. For the first try of receiving a response, a GNUTLS_EAGAIN error is received, and currently only check again if there is a timeout set. Otherwise, connection is closed immediately.
As workaround, it will try now up to 10 times before closing the connection.
**How**:
In debian buster TLS1.3 is the default one. Set an ospd-openvas server with connection type TLS. Add the scanner to gvmd. Start a Task. It should end successfully. Without the patch, the connection is closed and the task is set as done with errors.
**Checklist**:

Retry if response via tls1.3 is still not received.

---

CHANGELOG.md
boreas/alivedetection.c
boreas/alivedetection.h

**What**:
Reduces time of alive test if target list is small.
**Why**:
To reduce the time of tests.
**How**:
Read the logs when doing a scan of 1 host. Previously scan took about 9 second, now it takes about 5 seconds.
**Checklist**:

Reduce timout for alive tests

---

CHANGELOG.md
base/networking.c
boreas/ping.c

**What**:
Set source address correctly and do not try to send ARP to unreachable destination when using test_alive_hosts_only feature. 
**Why**:
To get expected behavior.
**How**:
The correct source address is printed in the debug logs. When trying to send to an unreachable destination a warning log is printed.
**Checklist**:

Improvements and fixes for test_alive_hosts_only feature

---

CHANGELOG.md
gmp/gmp.c
gmp/gmp.h

This is not required anymore and can be removed
after https://github.com/greenbone/gsa/pull/2448
is applied as well as a backport of that PR to the
gsa master branch.
**Checklist**:

Remove handling of severity class from auth

---

CHANGELOG.md
base/hosts.c
base/hosts.h
boreas/boreas_io.c
boreas/boreas_io.h
boreas/util.c
util/kb.c
util/kb.h
util/xmlutils.c

**What**:
If the flag to indicate that the alive test has finished has been already set at the end of the list, with these changes it is possible to add/move a host and then re allocate the flag at the end again.
**Why**:
In some cases a host can be added/moved in the alive host list.
**How**:
**Checklist**:

Allow to re allocate the finish flag in the hosts queue for alive tests.

---

CHANGELOG.md
base/nvti.c
base/nvti.h

This adds a handling for severities similar to refs.
**Checklist**:

Add multiple severities for nvti

---

CHANGELOG.md
base/hosts.c
base/hosts.h
base/hosts_tests.c

**What**:
Allows to put a host in the hosts structure at the end
of the host list without reset the iterator.
**Why**:
It was need to move the host to the end without resetting the iterator. 
**How**:
**Checklist**:

Add function to move a host to the end of the list

---

CHANGELOG.md
boreas/boreas_io.h
osp/osp.c
osp/osp.h
osp/osp_tests.c

**What**:
Add support for new OSP element for defining alive test methods via separate sub elements.
**Why**:
To have complete implementation of OSP.
**How**:
Added some tests.
**Checklist**:

Support new <alive_test_methods> OSP element 

---

CHANGELOG.md
base/nvti.c

**What**:
The tag names "severity_date" is treated special
**Why**:
For consistency, the severity_date  date format value is the same as for creation_date and last_modification. Internally is expected to be a seconds since epoch value.
**How**:
Add the following tags to a script
```
script_tag(name:"severity_vector", value:"CVSS:3.0/AV:L/AC:H/PR:H/UI:R/S:U/C:N/I:L/A:L");
script_tag(name:"severity_origin", value:"greenbone");
script_tag(name:"severity_date", value:"2009-03-26 19:23:59 +0100 (Thu, 26 Mar 2009)");
```
Check in redis cache, that the severity date for the modified script is seconds since epoch.
```
redis /tmp/redis.sock[1]> lrange nvt:1.3.6.1.4.1.25623.1.0.100081 0 -1
1) "auth_enabled.nasl"
2) ""
3) ""
4) ""
5) ""
6) "Services/auth, 113"
7) "find_service.nasl"
8) …
```

Convert "severity_date" value to seconds since epoch

---

CHANGELOG.md
CMakeLists.txt
base/CMakeLists.txt
base/cvss.c
base/cvss_tests.c
tests/CMakeLists.txt

**What**:
Add v3 handling to get_cvss_score_from_base_metrics.
**Why**:
Needed by gvmd for v3 severities.
**How**:
Run tests.  cvss-test should pass.
**Checklist**:

Add v3 handling to get_cvss_score_from_base_metrics

---

CHANGELOG.md
base/prefs.c

**What**:
Move all scanner settings/preferences which have defaults and are not dependent on CMake variables
to gvm-libs. This way they are available for openvas-nasl too.
Settings not moved to gvm-libs with reason
Defaults defined via CMake
* scanner_plugins_timeout
* plugins_timeout
* db_address
Defined via openvas-nasl command line option
* include_folders
Not needed by openvas-nasl
* plugins_folder
Prerequisite to:
https://github.com/greenbone/openvas/pull/614
**Why**:
To make the options available to scripts when run via openvas-nasl.
**How**:
Dump the prefs (`prefs_dump ()`) with and without the PRs.
openvas-nasl: has the additional options now.
openvas: no difference in preference settings. 
**Checklist**:

 Make more scanner preferences available for openvas-nasl

---

INSTALL.md
util/CMakeLists.txt

LDAP and RADIUS auth are both optional features:
https://github.com/bjoernricks/gvm-libs/blob/b0e1f5ef9916062a2b48b84004dc2922c2ef5a08/util/CMakeLists.txt#L94-L132
so we should document / mention them separately.
This can also help with questions like https://github.com/Atomicorp/gvm/issues/36
Part of https://github.com/greenbone/templates/issues/17

Restructure LDAP / RADIUS install instructions. Fix typo.

---

CHANGELOG.md
base/networking.c

**What**:
Add NULL checks.
man getifaddrs: This field may contain a null pointer.
**Why**:
Solves a segfault in networking_tests.c.
**How**:
```make tests && CTEST_OUTPUT_ON_FAILURE=1 make test``` should pass.  Seeing failure may depend on network setup.
**Checklist**:

Always NULL check ifaddrs->ifa_addr

---

CHANGELOG.md
osp/osp.c

**What**:
Pass name instead of value to g_has_table_remove.
**Why**:
Function expects key name.  Was causing a segfault on scans with credentials where the credential could not be decoded.
**How**:
Run gvmd with --disable-encrypted-credentials.  Create a target with an SSH credential.  Run a task using the target.  Task should run.
**Checklist**:

Correct g_hash_table_remove arg

---

CHANGELOG.md
util/fileutils.c
util/fileutils.h

**What**:
The new functions gvm_file_exists, gvm_file_is_executable and
gvm_file_is_readable are added as an alternative to g_file_test that
tests the file access according to the effective user and group ID
instead of the real one.
**Why**:
The change is required for gvmd to work properly with the file flags
to set the UID and GID
**How**:
I tested the functions with a small test program like this:
```c
#define _GNU_SOURCE
#include <stdio.h>
#include <unistd.h>
#include <gvm/util/fileutils.h>
int main ()
{
const char *fname = "./test.txt";
printf ("File: %s\n", fname);
printf (" - exists: %d\n", gvm_file_exists (fname));
printf (" - readable: %d\n", gvm_file_is_readable (fname));
printf (" - executable: %d\n", gvm_file_is_executable (fname));
printf ("eUID: %d, eGID: %d\n", geteuid(), …
```

Add file access tests using effective UID/GID (20.08)

---

base/logging.c
base/networking.c
boreas/boreas_io.c
osp/osp.c
util/kb.c
util/serverutils.c

**What**:
Fix warnings of static code analysis.
**Why**:
Improve code quality and make CI happy.
**How**:
Install `clang-tools-7` and run static code analysis with e.g.:
`mkdir build && cd build/ && /bin/scan-build-7 cmake -DCMAKE_BUILD_TYPE=Debug .. && /bin/scan-build-7 -o tmp/scan-build-report make && [ -z "$(ls -A tmp/scan-build-report/)" ]`
**Checklist**:

Fix static code analysis warnings

---

CHANGELOG.md
base/hosts.c
base/hosts_tests.c

**What**:
Accept underscore as valid char in hostname strings
**Why**:
Underscore is allowed for domain names, but not for hostnames. Despite it is not recommended at all, it can be desirable to use it. Under the premise "the scanner must do the best it can" it is now allowed.
RFC for hostnames: https://tools.ietf.org/html/rfc819
RFC for domain name syntax https://tools.ietf.org/html/rfc2181
**How**:
Scan a target which includes a host with an underscore in the name
**Checklist**:

Accept underscore as valid char in hostname strings

---

CHANGELOG.md
boreas/alivedetection.c
boreas/cli.c
boreas/ping.c
boreas/util.c
boreas/util.h

**What**:
Make sure that we do no try to send when the SO_SNDBUF is already full.
**Why**:
Packets might not be sent if no buffer space is available.
**How**:
Disabale rate limit by setting BURST_TIMEOUT to 0 (needs recompile) and use `tc` to limit bandwidth e.g. ``sudo tc qdisc add dev <iface> root tbf rate 500kbit burst 32kbit latency 400ms`` and use boreas (https://github.com/greenbone/boreas/) `sudo boreas --target "198.18.0.0/15,172.16.0.0/12,192.168.0.0/16" --icmp`.
Before the patch you would see a lot of `sendto(): No buffer space available`. After the patch they are gone.
**Checklist**:

Add throttle functionality for sending pings

---

CHANGELOG.md
base/networking.c
boreas/util_tests.c

**What**:
* I hope this fixes #433 , actually the compiler is very old, I tried to compile with the same compileoptions `-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -g -Wall -Wextra -Werror    -std=gnu99` but the warning did not pop up in gcc-8 nor clang-7.
**Why**:
**How**:
**Checklist**:

Initialize struct

---

CHANGELOG.md
base/networking.c

**What**:
* Fixing the warning in #434 .
* tested with clang-7 and gcc-8
(Now the correct Branch to merge ...)
**Why**:
**How**:
**Checklist**:

Fixing clang compiler warning, because of double parentheses

---

CHANGELOG.md
INSTALL.md
boreas/CMakeLists.txt
boreas/arp.c
boreas/arp.h
boreas/ping.c

**What**:
Use libnet for arp ping for alive detection.
**Why**:
Robust implementation of arp ping as it was not stable before. The arp ping is part of the experimental (currently default off) alive detection feature.
**How**:
Can be tested with cli front-end for the alive test https://github.com/greenbone/boreas/ and do some scans with it. 
`sudo boreas --target "0:0:0:0:0:ffff:c0a8:384b,192.168.42.42" --arp`
**Checklist**:

Improve ARP ping

---

CHANGELOG.md
util/kb.c

**What**:
Use a char pointer instead of an zero-lenght array as kb_redis struct member.
Use g_strdup instead of strncpy for initializing kbr->path.
Free the path where necessary.
**Why**:
> Declaring zero-length arrays in other contexts, including as interior members of structure objects or as non-member objects, is discouraged. Accessing elements of zero-length arrays declared in such contexts is undefined and may be diagnosed.
https://gcc.gnu.org/onlinedocs/gcc/Zero-Length.html
**How**:
**Checklist**:

Code improvement. Also fix compiler warning.

---

boreas/ping.c
boreas/util.c

From codespell:
```
./boreas/util.c:644: timout ==> timeout
./boreas/ping.c:92: succes ==> success
./boreas/ping.c:132: occure ==> occur, occurred
```

Fix typos.

---

CHANGELOG.md
base/logging.c
base/logging.h

**What**:
Do not abort when trying to log to log file with wrong permissions.
If the error reported by setup_log_handlers is not handled the log domains with log files which can not be accessed will be ignored and some default is used instead.
Related to: https://github.com/greenbone/openvas-scanner/pull/661 
**Why**:
Fix https://github.com/greenbone/openvas-scanner/issues/415.
**How**:
**Checklist**:

Do not abort when log file not accessible

---

CHANGELOG.md
base/logging.c

**What**:
Adds missing handling of syslog logging and empty file string to https://github.com/greenbone/gvm-libs/pull/447 .
**Why**:
Else not able to init openvas with some logging configs.
**How**:
add the following to the openvas_log.conf
```
[sd   main]
prepend=%t %s %p
separator=:
prepend_time_format=%Y-%m-%d %Hh%M.%S %Z
file=syslog
syslog_facility=daemon
syslog_indent=openvas
level=127
```
Without the patch `openvas -s` will fail if openvas is started as other user (e.g. `sudo -u testuser openvas -s`). Same if `file=` is put into the config. With applied PR this is fixed.
**Checklist**:

Fix log file check

---

CHANGELOG.md
util/kb.c

**What**:
Use memory purge redis command when initializing new kb.
**Why**:
Handle issue of redis memory not being released to the OS again.
**How**:
Running the following script with a target of 5 hosts with ospd-openvas. Redis will use about 800M memory. 
```C
if(description) {
script_oid("1.3.6.1.4.1.25623.1.0.999999");
script_version("2019-09-09T06:03:58+0000");
script_name("test redis memory");
script_category(ACT_SCANNER);
script_family("Port scanners");
script_copyright("This script is Copyright (C) 2009 Greenbone Networks GmbH");
script_tag(name:"last_modification", value:"2019-09-09 06:03:58 +0000 (Mon, 09 Sep 2019)");
script_tag(name:"creation_date", value:"2009-10-26 10:02:32 +0100 (Mon, 26 Oct 2009)");
script_tag(name:"cvss_base", value:"0.0"); …
```

Use memory purge redis command when initializing new kb

---

CHANGELOG.md
base/logging.c

**What**:
Split the log message into smaller pieces when syslog is the log destination
**Why**:
Syslog doesn't support messages longer than 1kb. The overflow data
will not be logged or will be shown in the hypervisor console
if it runs on a virtual machine.
**How**:
- Set max-ips-per-target to 70000 in gvmd
- Create a target with 70000 hosts
- Set the syslog as log facility
- Run the task and check that the 70000 host are logged in different messages.
**Checklist**:

Split the log message into smaller pieces when syslog is the log destination

---

CHANGELOG.md
util/kb.c
util/kb.h

**What**:
Add support for volatile keys.
Used by https://github.com/greenbone/openvas-scanner/pull/682.
**Why**:
See https://github.com/greenbone/openvas-scanner/pull/682 for details.
**How**:
See https://github.com/greenbone/openvas-scanner/pull/682 for details.
**Checklist**:

Add support for volatile keys

---

CHANGELOG.md
boreas/boreas_io.c

**What**:
Fix finish_signal_on_queue. Check for the signal in the whole items under the key, instead of
just checking the the last item.
**Why**:
In some cases the `finished` was not reallocated causing interrupted scans
**How**:
Run a scan with Boreas alive test, with `expand_vhosts` option enabled and `allow_simultaneous_ips` disabled. Check that the scan is not interrupted and all hosts are scanned.
**Checklist**:

Fix finish_signal_on_queue

---

CHANGELOG.md
boreas/alivedetection.c
boreas/boreas_io.c
util/ldaputils.c

**What**:
Do not start sniffer thread if only consider alive was chosen for alive test.
**Why**:
Small Speed improvement for alive scanning.
**How**:
Run simple scan before and after applied PR. Should be a difference of 1-2 seconds for the alive detection.
**Checklist**:

Do no start sniffer thread unnecessarily 

---

boreas/alivedetection.c

**What**:
Fixed small spelling mistake.
**Why**:
The mistake caused some warnings at build-time in GOS (Closes: GOS-52).
**How**:
N/A
**Checklist**:

Fixed small spelling mistake (PL-52)

---

CHANGELOG.md
util/kb.c

**What**:
Ensure that new kb taken by the scanner are always clean.
**Why**:
To ensure that new kbs taken by the scanner are always clean.
**How**:
Enter to redis-cli and check that the only kb set "in used" is the kb 1, which contains the VTs cache
```
$ redis-cli -s /run/redis-openvas/redis.sock 
redis /run/redis-openvas/redis.sock> keys *
1) "GVM.__GlobalDBIndex"
redis /run/redis-openvas/redis.sock> HGETALL GVM.__GlobalDBIndex
1) "1"
2) "1"
```
Add some items to the the KB 2 and KB 3
```
redis /run/redis-openvas/redis.sock> SELECT 2
OK
redis /run/redis-openvas/redis.sock[2]> LPUSH a 123 1231 11222
(integer) 3
redis /run/redis-openvas/redis.sock[2]> LPUSH b 123 1231 11222
(integer) 3
redis /run/redis-openvas/redis.sock[2]> LPUSH b 123 1231 11222
(integer) 6
redis …
```

Ensure that new kb taken by the scanner are always clean.

---

CHANGELOG.md
base/nvti.c
base/nvti.h

**What**:
The typedef and the functions nvti_severity_score, vtseverity_new and
vtseverity_new now use double to be able to handle CVSS scores.
**Why**:
The score handling in gvmd will use CVSS scores instead of integer ones.
**How**:
Tested by running gvmd --rebuild in an updated gvmd that uses CVSS scores and checking that scores are not truncated to integers.
**Checklist**:

Use double for scores in vtseverity_t and helpers

---

CHANGELOG.md
boreas/alivedetection.c

**What**:
Validate for max_scan_hosts scanner preference.
**Why**:
To ensure that the value is an integer and  greater than 0.
Otherwise, set the default value MAX_INT.
**How**:
**Checklist**:

Validate for max_scan_hosts scanner preference.

---

CHANGELOG.md
base/hosts.c
base/hosts.h

**What**:
Add function to find and return a host from a host list.
**Why**:
To have access to host in a host list, if it exists.
**How**:
**Checklist**:

Add function to find and return a host from a host list.

---

CHANGELOG.md
util/passwordbasedauthentication.c
util/passwordbasedauthentication_tests.c

To make it easier to handle hash or passqord unset cases for the caller
gvm-libs passwordbasedauthentication should not threat hash or password
is a nullpointer as an error case but rather as a invalid password.
**What**:
**Why**:
**How**:
**Checklist**:

When hash or password are NULL return INVALID rather then ERR

---

CHANGELOG.md
util/kb.c

**What**:
Dont free the kb_path twice.
**Why**:
The functions calling g_strdup (kb_path) already take care of free()'ing the string, as well as delete once the kb is deleted.
**How**:
Kill redis and call openvas in the console. 
```
$ openvas
(process:26189): GLib-WARNING (recursed) **: Invalid UTF-8 passed to g_io_channel_write_chars().Aborted
```
You can run `valgrind openvas ` and check it.
**Checklist**:

Dont free the kb_path twice.

---

CHANGELOG.md
base/prefs.c

**What**:
Make test_alive_hosts_only (Boreas) feature the new default.
**Why**:
**How**:
**Checklist**:

Make test_alive_hosts_only (Boreas) feature the new default

---

CHANGELOG.md
base/CMakeLists.txt

**What**:
The directory for Sentry was missing in the include_directories in
CMakeLists.txt.
A typo has been fixed in the "Building with Sentry integration" message.
**Why**:
**How**:
By running CMake with `BUILD_SENTRY=1` and then trying to build gvm-libs.
**Checklist**:

Fix include dirs for Sentry and fix typo

---

CHANGELOG.md
util/CMakeLists.txt
util/mqtt.c

**What**:
Search for paho-mqtt3c instead of lpaho.
**Why**:
Does not install with MQTT support otherwise.
**How**:
Install gvm-libs.
**Checklist**:

Fix find_library call

---

CHANGELOG.md
base/hosts.c

**What**:
If the array memory for the hosts is reallocated, the new memory is
initialized with all \0 bytes.
**Why**:
This ensures the array is correctly terminated when gvm_hosts_fill_gaps
is called when excluding hosts.
**How**:
By creating multiple targets with very large host ranges (> 2 million hosts) and adding excluded hosts to at least one of them.
**Checklist**:

Initialize reallocated memory in gvm_hosts_add

---

CHANGELOG.md
base/hosts.c

**What**:
If the array memory for the hosts is reallocated, the new memory is
initialized with all \0 bytes.
This is a backport of #520.
**Why**:
This ensures the array is correctly terminated when gvm_hosts_fill_gaps
is called when excluding hosts.
**How**:
**Checklist**:

Initialize reallocated memory in gvm_hosts_add (21.04)

---

CHANGELOG.md
base/hosts.c

**What**:
If the array memory for the hosts is reallocated, the new memory is
initialized with all \0 bytes.
This is a backport of #520.
**Why**:
This ensures the array is correctly terminated when gvm_hosts_fill_gaps
is called when excluding hosts.
**How**:
**Checklist**:

Initialize reallocated memory in gvm_hosts_add (20.08)

---

CHANGELOG.md
boreas/boreas_io.c

**What**:
Do not send unnecessary message anymore.
When 0 alive hosts are left to scan and max_scan_hosts limit is reached no message will be generated for that case anymore.
**Why**:
SC-298
**How**:
Start a scan with 1 host and `max_scan_hosts = 1` and `test_alive_hosts_only = yes`. Before PR a Error Message message about 0 left alive hosts is generated. After PR no message in generated anymore.
**Checklist**:

Do not send unnecessary message

---

CHANGELOG.md
util/mqtt.c
util/mqtt.h

**What**:
**Why**:
**How**:
**Checklist**:

[middleware] Add function for mqtt init status

---

CHANGELOG.md
base/nvti.c
base/nvti.h
base/nvti_tests.c

**What**:
Add function to get the severity_vector, otherwise the cvss_base_vector.
**Why**:
Extended severity was introduced and there are new tags to hold severity information. severity_vector is the tag name.
Some VTs doesn't have the new tag, but the old one cvss_base_vector. This function returns the vector severity_vector, or the cvss_base_vector if the vt does not have the new tag.
**How**:
Test added
**Checklist**:

Get vector

---

CHANGELOG.md
util/mqtt.h

**What**:
Fix strict prototypes
**Why**:
Avoid warning/error when the compiler uses the -Werror=strict-prototypes flag
**How**:
**Checklist**:

Fix prototype

---

CHANGELOG.md
base/hosts.c
base/hosts.h

**What**:
Added a duplicate function for host and vhost.
https://github.com/greenbone/openvas-scanner/pull/888 depends on this PR
**Why**:
In some cases a Segmentation Fault appears when freeing the hosts and vhosts of hosts and alive_hosts_list.
**How**:
**Checklist**:

Fix free host segfault

---

.docker/build.Dockerfile
.github/workflows/ci-c.yml

**What**:
With using Debian stable (Bullseye) a package of libcgreen is available
and it isn't required to build it ourselfs.
**Why**:
We use Debian Bullseye for the container images which provides a package for libcgreen.
**How**:
**Checklist**:

Install libcgreen unit test library via Debian

---

base/logging.c

**What**:
Make sure to always init logger mutex before use.
Previously it could be the case that the mutex was not yet inited when openvas-scanner calls `gvm_log_lock` in `create_process`.
See https://github.com/greenbone/openvas-scanner/issues/960.
Jira: SC-468
**Why**: 
Prevent segfault.
**How**:
**Checklist**:

Always init logger mutex before use

---

boreas/sniffer.c

**What**:
Fix potential dead lock
**Why**:
Bug issue: https://github.com/greenbone/gvm-libs/issues/639
jira: SC-490
**How**:
Add `sleep(1)` before `pthread_mutex_lock` in `start_sniffer_thread()` to simulate described erroneous behavior of https://github.com/greenbone/gvm-libs/issues/639.
After fix everything should be working as intended.
**Checklist**:

Fix potential dead lock

---

base/networking.c
base/networking.h
boreas/arp.c

**What**:
Add new/simpler method for getting the outgoing interface for a destination.
Use that new method for the arp ping implemenation in boreas.
jira: SC-499
**Why**:
The wrong interface was chosen for the arp ping.
Maybe the new method can replace the old method in other places in the future too.
**How**:
Use boreas for testing the arp ping.
Set debug level to 128 in `<installprefix>/etc/boreas/boreas_log.conf`. Logs are located in `<installprefix>/var/log/gvm/boreas.log`
Run boreas with targets which are routet through different interfaces. E.g.:
`sudo boreas --arp --target "192.168.178.43,192.168.56.100,127.0.0.1"`
See in the logs information about every ping. Interface is listed there. Check if it is the correct interface.
With my system interface configuration I got the wrong …

Add new method for detecting outface and use it in arp ping

---

osp/osp.c
osp/osp.h

**What**:
This adds new functions to get extended information about the NVTs feed via OSP.
**Why**:
So gvmd can get the info from the scanner instead of calling greenbone-nvt-sync directly.
(AP-1845)
**How**:
By running the `<get_feeds/>` GMP command with the changes from greenbone/gvmd/pull/1769.
**Checklist**:

Add functions osp_check_feed and osp_get_vts_feed_info

---

base/hosts.c

**What**:
Add preprocessor directives to check if glibc is used in the system (default in the reference system), since malloc_trim() is not available in other system, like Alpine which uses musl libc
Jira: SC-549
**Why**:
Resolves #284 
**How**:
**Checklist**:

Check for malloc_trim() support.

---

util/kb.c

**What**:
Log warning when Redis tcp connection is used
Jira: SC-550
**Why**:
Redis TCP connection is not encrypted
**How**:
Set redis and openvas to use a tcp connection and check the logs.
**Checklist**:

Add: Log warning when Redis tcp connection is used

---

util/mqtt.c

**What**:
Handle error of `mqtt_connect`
SC-566
**Why**:
When `mqtt_connect` failed, no error was returned and openvas thought the MQTT connection was successful even when it was not.
**How**:
Start a scan without a broker. Compare before patch and after. Before yout get these messages:
```
libgvm util:CRITICAL:2022-03-23 09h26.41 utc:4416: mqtt_connect: mqtt connection error to tcp://127.0.0.1:1883: Failure
sd   main:MESSAGE:2022-03-23 09h26.41 utc:4416: attack_network_init: INIT MQTT: SUCCESS 
```
after the patch you get
```
sd   main:MESSAGE:2022-03-23 10h34.47 utc:21180: Running LSC via Notus for 127.0.0.1
libgvm util:CRITICAL:2022-03-23 10h34.47 utc:21180: mqtt_connect: mqtt connection error to tcp://127.0.0.1:1883: Failure
libgvm util:WARNING:2022-03-23 10h34.47 utc:21180: …
```

Fix: return with error code when mqtt connect fails

---

boreas/alivedetection.c
boreas/ping.c
boreas/sniffer.c

To reduce the chances of having hosts wrongfully identified as dead via ICMP the amount of sent icmp packets got enhanced by 10 and the wait overall grace period got increased by 3 to reduce the chances on slower networks.

Improve boreas retry functionality SC 434

---

base/proctitle.c
base/pwpolicy.c

In some scans it can happen that the program name will go over 256 may
resulting in segmentation faults. To counter that we set the maximal
program name to 256 to avoid malloc or segmentation faults.

Fix: instead of setting strlen of argc just assume _POSIX_PATH_MAX 256 

---

base/proctitle.c
base/pwpolicy.c

According to C99:
```
The parameters argc and argv and the strings pointed to by the argv array shall
be modifiable by the program, and retain their last-stored v alues between program
startup and program termination.
```
This means that only the data in argv is guaranteed to be writeable; everything else is not specified and may be different depending on the execution context and machine.
The previvous solution used the space `environ` by allocating a new environ block and move the memory. This however is also not guaranteed and has lead to segmentation faults and is according to `man 7 environ` in BUGS:
```
There  is also the risk of name space pollution.  
Programs like make and autoconf allow overriding of default utility names from the environment with similarly named variables in …
```

Fix: limit proctitle to argv space

---

changelog.toml

To be able to create a changelog from conventional commits we need to
define which commits should be parsed within a changelog.toml.

Refactor: add changelog.toml

---

INSTALL.md
util/CMakeLists.txt

**What**:
MQTT support is required for openvas-scanner. It would be possible to
just not build the mqtt support in gvm-libs but in that case it would
be required to check in openvas-scanner if gvm-libs has mqtt support.
Therefore it is easier to always build gvm-libs with mqtt support.
Closes #694
**Why**:
libpaho is already required see #694 and #632
**How**:
```sh
apt remove libpaho-mqtt-dev
mkdir build &&cd build
cmake ..
```
cmake configuration fails with an error.
**Checklist**:

Fix: Require libpaho for mqtt support

---

.github/workflows/build-container.yml

**What**:
Split building build and production container images
**Why**:
The build image really rarely needs a rebuild. Therefore split this job
into an own workflow and only rebuild if the corresponding dockerfile or
workflow has changed.
**How**:
**Checklist**:

Change: Split building build and production container images

---

.github/workflows/container.yml

**What**:
Use matrix to trigger dependent image builds in parallel
DEVOPS-404
**Why**:
Simplify triggering dependent container image builds by using a workflow matrix.
**How**:
**Checklist**:

Use matrix to trigger dependent image builds in parallel

---

.github/workflows/container.yml

**What**:
Use new trigger-workflow action to update dependent images
**Why**:
When the gvm-libs container has re-build all dependent images should be re-build too.
DEVOPS-404
**How**:
**Checklist**:

Change: Use new trigger-workflow action to update dependent images (stable)

---

boreas/boreas_io.c

**What**:
Consider the alive_test_ports scanner preference in lowercase. 
Jira: SC-689
**Why**:
The option is now visible in the GUI and gvmd shows this option in lower case as scanner preference, which is not handle by ospd-openvas and stored in redis directly.
This doesn't change the previous behaviour and both preferences (upper and lower case) are supported. 
**How**:
**Checklist**:

Consider the alive_test_ports scanner preference in lowercase.

---

base/prefs.c
boreas/alivedetection.c
boreas/alivedetection.h
boreas/boreas_io.c
boreas/boreas_io.h
boreas/cli.c
boreas/cli.h

**What**:
Make optional the waiting for replies timeout. This doesn't change the original behavior if not set. 
Setting this in the openvas.conf, change the default value system wide.
Jira: SC-680
**Why**:
Some deveices or networks are too slow, and replies are not get in time, and therefore the target considered dead.
**How**:
Set the scanner preference (in GSA in the scan config, or in the openvas.conf configuration file). Run a scan against dead hosts and see the logs, how long  it takes to finished the alive scan.
**Checklist**:

Add: Boreas timeout option

---

util/CMakeLists.txt

**What**:
Use pkg-config to search for libgpgme and libgcrypt
Closes #720
**Why**:
Both libraries are shipped with .pc files in bullseye. Therefore it is easier and better to use pkg-config to check their availability and compiler settings instead of maintaining our own cmake code.
**How**:
Tested building gvm-libs with a debian bullseye container image.
**Checklist**:

Change: Use pkg-config to search for libgpgme and libgcrypt

---

util/ldaputils.c

LDAP version is by default set to 3, but when StarTLS is disabled then the initialization is done for the second time. And after the initialization version is set to 2. This change is to set the version back to 3.
Signed-off-by: Franciszek Klajn <fklajn@opera.com>
**What**:
LDAP version setting bugfix
jira: T4-398
**Why**:
Because without the change LDAP authentication over LDAPS is not possible on recent Linux distribution.
**How**:
The change has been tested on a test system (Debian Bullseye).
**Checklist**:

Set LDAP version to 3 after initialization

---

base/networking.c

**What**:
The following error is happening on Ubuntu Lunar (development
version):
```
In function ‘ip_islocalhost’,
inlined from ‘gvm_routethrough’ at ./base/networking.c:1032:11:
./base/networking.c:863:22: error: ‘addr6.__in6_u.__u6_addr32[3]’ may be used uninitialized [-Werror=maybe-uninitialized]
./base/networking.c: In function ‘gvm_routethrough’:
./base/networking.c:790:19: note: ‘addr6.__in6_u.__u6_addr32[3]’ was declared here
```
**Why**:
GCC 12 is more strict when checking for uninitialized variables.
**How**:
I rebuilt gvm-libs in Ubuntu with the proposed patch, and the build is
now passing.
**Checklist**:

Fix -Werror=maybe-uninitialized on GCC 12

---

base/logging.c
base/logging.h

Sets reference in logging.c to static to prevent wrongful compiler
optimizations on initialization.
This is an attempt to fix: https://github.com/greenbone/gsad/issues/115

Fix: set reference to static

---

base/networking.c
base/prefs.c
base/proctitle.c
osp/osp.c
util/passwordbasedauthentication.c

When copying strings with memcpy in places where strncpy was used before, use the size of the source string instead of the destination size.
Using the destination size can cause errors if it is larger than the source size.

Fix: Use source size copying strings with memcpy

---

util/ldaputils.c
util/ldaputils.h

This adds extended LDAP functions for an option to force LDAPS for authentication
The normal LDAP port may be blocked by a firewall, in which case only the LDAPS port should be tried.
GEA-82

Add option to force LDAPS for authentication

---

.github/workflows/release-pontos.yml

Update release workflow to create patch releases for stable
Using calendar would create a new 23.X.Y release. For the stable branch we just want to increment the patch version.

Fix: Update release workflow to create patch releases for stable

---

util/xmlutils.c
util/xmlutils.h

The new `element_to_string` function can be used to save an XML element as a string, including inherited namespaces.
This required to store the original XML of SCAP data in the gvmd database.
GEA-138
used by greenbone/gvmd#1935

Add: XML element_to_string function

---

util/authutils.c
util/authutils.h

Implemented a function that generates a hash value for an arbitrary string.
This function is needed for GEA-51 to catch duplicated results in reports.
Addresses GEA-51.

Generate a hash value for a given string.

---

.docker/prod.Dockerfile
.github/workflows/container.yml
osp/osp.c

Adapt docker images
Pushes the version tags to docker hub on a tag release
- greenbone/gvm-libs:${major}
- greenbone/gvm-libs:${major.minor}
- greenbone/gvm-libs:${major.minor.patch}
This will allow container users to choose the newest 22 without
having to adapt to each minor or patch version manually. If the
latest 22 is buggy, they can jump back to either a patch or a minor
version until there is a new 22 version that fixes it.
When the tag version is the highest major version and is not the first
major release with minor and patch version is 0 than it also creates a
latest and stable tag.
Just to give an overview, here are some examples:
Release 22.5.1 on greenbone/gvm-libs would result in the
following tags:
- greenbone/gvm-libs:22
- greenbone/gvm-libs:22.5
- greenbone/gvm-libs:22.5.1 …

Adapt Docker build and fixes a bug that assumes size_t is unsigned long

---

base/networking.c
util/kb.c

Use `g_memdup2` instead of `g_memdup` if the glib version is new enough.
There's a vulnerability in `g_memdup` with large sizes, so we may as well use `g_memdup2`.  And this removes the build warnings.
Glib announcement: https://discourse.gnome.org/t/port-your-module-from-g-memdup-to-g-memdup2-now/5538
PR that made the build pass with the warnings: greenbone/gvm-libs/pull/605

Use g_memdup2 when available

---

osp/osp.c
osp/osp.h
util/xmlutils.c
util/xmlutils.h
util/xmlutils_tests.c

Adds function `osp_get_vts_ext_str`.  Like `osp_get_vts_ext`, but returns a string instead of an entity tree.
Allows the caller to choose the XML parser.
Required by https://github.com/greenbone/gvmd/pull/1959.

Add osp_get_vts_ext_str

---

base/nvti.c
base/nvti.h

Add "put" versions of the `nvti_t` setter functions, like `nvti_put_name` for `nvti_set_name`.
The put versions use the given string directly, instead of allocating a copy of the string.
These are useful if you have already allocated the string, to save memory allocations.
Required by greenbone/gvmd/pull/1959.
Waits for #767.

Add nvti set functions that use the given string

---

util/xmlutils.c

In these two functions only offer nodes of type "ELEMENT", skipping other types of nodes like "ATTRIBUTE" and "TEXT".
This closes a bug in the element interface where the functions were returning attributes, text, etc but they are supposed to match `next_entities` and `first_entity`, which only return entities.
Existing usage in gvmd manage_sql_secinfo.c has always been safe because it always checks the name of an element before using the element.
Required by https://github.com/greenbone/gvmd/pull/1959.
Waits for #768.

Restrict element_first_child and element_next to element nodes.

---

osp/osp.c
util/xmlutils.c
util/xmlutils.h
util/xmlutils_tests.c

1. Add a dedicated function, `read_text_c`, for skipping the XML parsing when reading from a server.
2. Use this new function in `osp_send_command_str` instead of using `read_entity_and_string_c`.
3. Revert the changes to `read_entity_and_string_c` made in #767.
The new function handles both socket and TLS cases.
The changes to `read_entity_and_string_c` removed the XML validation, which may be required by callers.
Waits for #769.

Use new read function for osp_send_command_str

---

util/xmlutils.c

The libxml based parse_element function now parses the input with relaxed limits by using the XML_PARSE_HUGE option. 
This fixes problems with parsing larger XML files like the CPE dictionary.
GEA-208

Fix: Parse XML with XML_PARSE_HUGE option

---

.github/workflows/container.yml

Adjust triggering gvmd and gsad repos after new release
Trigger builds of gvmd and gsad container images after a new tag has been created.
GEA-196
https://github.com/greenbone/gvmd/pull/2005

Change: Adjust triggering gvmd and gsad repos after new release

---

base/credentials.h

The credentials struct now has a new field for the setting "Note/Override Excerpt Size".
This allows gvmd to cache the setting so it does not have to query the database for every reference to a note or override in a report.
GEA-86

Add: Add excerpt_size field to credentials_t

---

util/xmlutils.c

As debian testing is using a new version of gcc (13.1), the build process failed with a Werror=nonnull This is now fixed, by checking a value to be NULL after allocating.

Fix: container build for debian testing

---

base/hosts.c
base/hosts.h

Add gvm_reverse_lookup_only_excluded() and gvm_reverse_lookup_unify_excluded() This functions return a hosts structure containing the excluded hosts which did not satisfy the condition
Jira: SC-929
It is necessary to know the hosts which where removed from the original hosts list.

Add: Add new functions related to reverse lookup

---

base/pidfile.c

Make sure the dir exists when creating the PID file.
Also log the name of the file when creating the PID file fails.
This always catches me when I install from source.
Precedent in logging: https://github.com/greenbone/gvm-libs/blob/43bc281ab071f9d071c7f5f9a7ad8c9178871fb8/base/logging.c#L772

Change: Ensure dir exists in pidfile_create

---

base/nvti.c
base/nvti.h

Add missing const attributes to nvtpref_new.
Needed to prevent warning if caller passes in a const.

Add: missing const

---

boreas/alivedetection.c
boreas/boreas_io.c

When more than one alive test method is selected, boreas check for each one until the host is alive. This will be done also even if the "consider alive" methods is selected. 
Jira: SC-934
This patch improves boreas to not run other selected alive methods if "consider alive" method is set

Change: Don't perform alive tests if "consider alive" method is selected

---

util/mqtt.c
util/mqtt.h

Make authenticated connection to MQTT broker backward comaptible
With this path older scanner versions are still compatible with this gvm-libs version.

Change: make authenticated connection to MQTT broker backward comaptible

---

base/hosts.c
base/nvti.c
gmp/gmp.c
osp/osp.c
util/kb.h
util/mqtt.c
util/serverutils.c
util/xmlutils.c

Resolve warnings from Doxygen.
Neater.

Clear doxygen warnings

---

util/gpgmeutils.c
util/mqtt.c

Remove "g_" prefix from variable names.
It makes them look like they're part of glib.

Change: remove leading g_ that looks like glib

---

base/CMakeLists.txt

gvm-libs (22.8.0 and 22.9.0) fail to run tests when compiled with clang as compiler and lld as a linker
base/CMakeLists.txt lacks a link to math lib
https://bugs.gentoo.org/925932

Fix underlinking the math library; see https://bugs.gentoo.org/925932

---

.docker/prod-testing.Dockerfile
boreas/ping.c

Fix: boreas. Use sequence number 1
Close #812
Jira: SC-1064

Change: boreas. Use sequence number 1.

---

base/CMakeLists.txt
base/cvss.c
base/cvss.h
base/cvss_tests.c

The function get_cvss_score_from_base_metrics can now also calculate the score of CVSS 4.0 vectors.
To be able to use CVSS 4.0 in VTs.
GEA-529

Add: Allow getting score of CVSS 4.0 vectors

---

README.md

The badge now says "Documentation Coverage" to make it clear that it is not measuring test coverage.

Change label of CodeCov badge

---

base/logging.c
base/logging.h

Add the function `set_log_tz` to the logging API.
This lets the logging caller specify which timezone is used for all log message.

Add: set_log_tz

---

util/sshutils.c

Prevent a segfault in `gvm_ssh_public_from_private` when calling GMP GET_CREDENTIALS with `format="key"`.
Segfault bad.
Create a password credential.
```
o m m '<create_credential><name>segf</name><login>segf</login><password>segf</password></create_credential>'
```
Get the credential with format `key`:
```
o m m '<get_credentials format="key" filter="name=segf"/>'
```
Before the PR the response is empty and this happens in the log:
```
md manage:MESSAGE:2024-05-13 13h48.53 EDT:588564: Received Segmentation fault signal
md   main:MESSAGE:2024-05-13 13h49.25 EDT:588625: BACKTRACE: gvmd: Serving client(+0x70026) [0x5555555c4026]
```
After the PR the log is clear and the response is good:
```
<get_credentials_response status="200" status_text="OK">
<credential …
```

Fix: prevent segfault in gvm_ssh_public_from_private

---

.github/workflows/dependency-review.yml

Allow to create messages in a PR for the dependency review workflow
The workflow wants to write a message to the PR about the dependency review details. This requires the `pull-request: write` permission.

Allow to create messages in a PR for the dependency review workflow

---

CMakeLists.txt
util/CMakeLists.txt
util/cpeutils.c
util/cpeutils.h
util/cpeutils_tests.c

Added routines to read a v2.2-conformant URI of a CPE or a formatted string binding of a CPE into some kind of WFN struct. Added routines to convert the WFN struct into a formatted string binding or a CPE v2.2-conformant URI. Added routines to convert a formatted string binding into a v2.2-conformant URI and vice versa.
Also added a function, that takes two CPEs represented in CPE structs and checks if one of the CPEs matches the other one.
These routines are needed for direct matching.
GEA-622
GEA-624
Added some unit tests.

Add: Added conversion routines for different CPE notation formats.

---

INSTALL.md

#830 had added the package name on top but not included the Debian package name here
Obvious...
None

Doc: Add missing package name to apt-get install line in INSTALL.md

---

.github/workflows/container.yml

'Trigger update container images in related projects' are broken in gvm-libs for openvas-scanner and boreas
- openvas-scanner workflow is broken because container.yml has been renamed/removed
- boreas workflow is broken because gvm-libs now requires libssh-dev: https://github.com/greenbone/boreas/pull/67
- https://mattermost.greenbone.net/gb/pl/i8wqemtaubgozchdp8yhm8zper
- https://github.com/greenbone/gvm-libs/actions/runs/10904200164/job/30262026614
- https://jira.greenbone.net/browse/DEVOPS-1224
- https://github.com/greenbone/boreas/pull/67

Fix: Dynamically adapt to workflow file in openvas-scanner repo

---

.github/workflows/container.yml

Replace push-container.yml with control.yml
'Trigger update container images in related projects (greenbone/openvas-scanner)' Action still fails, because push-container.yml misses workflow_dispatch trigger.
Only found sbom-upload.yml or control.yml with the workflow_dispatch trigger in openvas-scanner.
Trying if the latter one is the correct one.
Alternatively, I started a search for the history of the container.yml file.
So there exists some dereferenced commit in openvas-scanner, which is foundable with:
`~/Greenbone/openvas-scanner/ > git log --all --full-history -- .github/workflows/container.yml `
This might be some clue why and how the workflow files have changed.
https://github.com/greenbone/gvm-libs/pull/834

Fix: Retry and Rename other workflow file for openvas-scanner, DEVOPS-1224

---

CMakeLists.txt
util/CMakeLists.txt
util/cpeutils.c
util/cpeutils.h

Added functions for the new CPE matching in CVE scans.
These new functions are needed for the new CVE scans with JSON match rules for CPE matching.
GEA-626

Add: Added functions for the new CPE matching in CVE scans.

---

.docker/prod-oldstable.Dockerfile

Add libcjson1 to oldstable Dockerfile
Builds using the resulting image can fail because of the missing dependency.

Fix: Add libcjson1 to oldstable Dockerfile

---

util/cpeutils.c
util/cpeutils_tests.c

When implementing GEA-635 we encountered a problem with a formatted string CPE that contained an escaped colon (e. g.) in the version part. This problem is fixed now.
This was a bug.
GEA-635

Fix: Fixed the problem with escaped colons in fs CPEs.

---

.docker/prod-oldstable.Dockerfile
CMakeLists.txt

The CMake option OPENVASD is added and used to disable building the openvasd library in the oldstable Docker images.
This is needed because openvasd would need a newer libcurl version.

Change: Disable build of openvasd for oldstable

---

openvasd/CMakeLists.txt

fix  https://github.com/greenbone/gvm-libs/issues/858
Only newer versions of libcurl provides the needed functions

Only libcurl 7.77.0 provides the needed functions.

---

INSTALL.md
openvasd/CMakeLists.txt
util/kb.h

A newer libcurl is required then stated and checked.
The curl function curl_easy_header is used which got introduced into libcurl with 7.83.0 according to
https://curl.se/libcurl/c/curl_easy_header.html.
Closes #861

Fix: Require libcurl >= 7.83.0

---

util/xmlutils.c

Adjust type for return from `xmlCtxtGetLastError`.
The libxml2 API changed.
libxml return type was changed in [61034116d0a3c8b295c6137956adc3ae55720711](https://github.com//GNOME/libxml2/commit/61034116d0a3c8b295c6137956adc3ae55720711).
See discussion [here](https://gitlab.gnome.org/GNOME/libxml2/-/commit/45470611b047db78106dcb2fdbd4164163c15ab7) and [here](https://gitlab.gnome.org/GNOME/libxml2/-/issues/622).
Closes #855.
1. Install libxml2 2.13.5 from source.
2. Ensure it's used
```patch
--- util/CMakeLists.txt
+++ util/CMakeLists.txt
@@ -34,7 +34,7 @@ pkg_check_modules (LIBSSH REQUIRED libssh>=0.6.0)
pkg_check_modules (REDIS REQUIRED hiredis>=0.10.1)
-pkg_check_modules (LIBXML2 REQUIRED libxml-2.0>=2.0)
+pkg_check_modules (LIBXML2 REQUIRED libxml-2.0>=2.13)
pkg_check_modules (GPGME …
```

Fix: add const for libxml2 2.12.0 API change

---

util/compressutils_tests.c

Pass `unsigned long` instead of `size_t` to the compression functions like `gvm_compress`.
It's the expected type.  On 32bit architectures like i386, using `size_t` leads to compile errors from `-Werror=incompatible-pointer-types`.
1. Setup [Debian 12 i386](https://portal.cloud.hashicorp.com/vagrant/discover/generic-x32/debian12) in VM
2. `cd $BUILD && cmake $SOURCE -D CMAKE_C_FLAGS=-m32 -D CMAKE_C_COMPILER=gcc -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON`
3. `cd $BUILD && make -B VERBOSE=1`
4. `cd $BUILD && make -B VERBOSE=1 tests`
Should see errors like:
```
path/to/compressutils_tests.c:88:63: error: passing argument 3 of ‘gvm_compress_gzipheader’ from incompatible pointer type [-Werror=incompatible-pointer-types]
88 |     gvm_compress_gzipheader …
```

Fix: Use unsigned long for compression lengths

---

base/nvti.c

Remove NULL cases from return docs.
`g_malloc0` aborts on allocation failure so these functions always return something.
Having the NULL might make people think they need to check the returns, which can lead to their callers needing to check returns etc.
https://docs.gtk.org/glib/func.malloc0.html
> If the allocation fails (because the system is out of memory), the program is terminated.
Note that `g_malloc0` can return NULL if the requested size is 0 but we are always passing a size > 0.

Fix doc: be accurate about allocated returns

---

openvasd/CMakeLists.txt

Don't require json-glib
json-glib as a requirement was introduced accidentally with the last gvm-libs release but isn't used at all. Therefore remove the dependency again.
Fixes #860
GEA-824

Fix: Don't require json-glib

---

INSTALL.md

Improve the installation documentation of gvm-libs.
* We support Debian stable and not a specific Debian version officially (even if GOS still uses oldstable as its base).
* Dependency lists can be checked easier if they are sorted
* Use Markdown finally

Update install docs

---

CMakeLists.txt
openvasd/CMakeLists.txt
openvasd/openvasd.c
openvasd/openvasd_tests.c

In `openvasd_parsed_results`, get `detail_source_*` from `detail > source > *`, instead of from  `detail > value > *`.
This seems to be the intention, according to the API and rust code.
Note that this also catches a problem where `cJSON_GetObjectItem (detail_obj, "type")` could have been called when `detail_obj` was NULL.

Fix: openvasd: get result detail source from right place

---

openvasd/openvasd.c

In `openvasd_start_scan` move the `Error parsing ... ID` warning out of the `if` so that the warning is printed even when there is an error message from `cJSON_GetErrorPtr`.
Sometimes the error message from `cJSON_GetErrorPtr` is an empty string, for example when there is an error connecting to the scanner. This makes it hard to locate the problem.
Note that this is a small helper fix. The real issue is that all the callers of `openvasd_send_request` are only checking the return for `RESP_CODE_ERR` (-1) when the return can also be eg 403. There are many of these so the fix needs some planning and a bigger PR.

Move openvasd_start_scan warning up in case the cJSON err is empty

---

openvasd/CMakeLists.txt

Remove `GLIB_JSON_*` references from CMakeLists.txt.
We're using cJSON now.
Missed in /pull/863.

Fix: remove stray json-glib config

---

openvasd/openvasd.c
openvasd/openvasd_tests.c

Fix: start time and end time when parsing scan status
Also, split a function for testing purposes. Add a test.
Was always set to 0 because a wrong comparison

Scan start end time

---

openvasd/CMakeLists.txt
openvasd/openvasd.c
openvasd/vtparser.c
util/json.c
util/json.h
util/json_tests.c

Add `gvm_json_obj_double` to `json.c`, and use it in `openvasd.c` and `vtparser.c`.
This is neater than using the three line cJSON snippet.
A nice side effect is that this removes many assignments that were happening inside `if` conditions.
Related: /pull/852

Add: gvm_json_obj_double

---

openvasd/openvasd.c
openvasd/vtparser.c
util/json.c
util/json.h
util/json_tests.c

Add `gvm_json_obj_str` to `json.c`, and use it in `openvasd.c` and `vtparser.c`.
This is neater than using the three line cJSON snippet.
As with `gvm_json_obj_double`, this removes many assignments that were happening inside `if` conditions.
Similar to /pull/876.

Add: gvm_json_obj_str

---

util/cpeutils.c
util/cpeutils.h
util/cpeutils_tests.c

The new function uri_cpe_to_uri_product is added to the CPE utilities.
This is needed for the new CVE scanner in gvmd.
GEA-885

Add: New function uri_cpe_to_uri_product

---

.github/workflows/container.yml

Don't trigger external CI workflows anymore
The triggered workflows are all obsolete and removed now. We don't use any build images anymore. Instead we build directly on images from gvm-libs without the need of dedicated build images per component.

Don't trigger external CI workflows anymore

---

openvasd/openvasd.c
openvasd/vtparser.c
util/json.c
util/json.h
util/json_tests.c

Add `gvm_json_obj_int` to `json.c`, and use it in `openvasd.c`.
Also add `gvm_json_obj_check_int`, and use it in `openvasd.c` and `vtparser.c`. This variant allows you to know if the int field was present, and to get the int at the same time.
These are neater than using the cJSON snippets. They're similar to `gvm_json_obj_str`.
As with `gvm_json_obj_double`, this removes assignments that were happening inside `if` conditions.
`gvm_json_obj_check_int` is only used twice but there will be a `gvm_json_obj_check_str` that is used more.
It's handy to have both the regular version and the `check` version because the regular version saves having to create a variable, but in some cases we need to know if the field exists before using it.
Similar to /pull/876 and /pull/877.

Add: gvm_json_obj_int

---

openvasd/openvasd.c
openvasd/vtparser.c
util/json.c
util/json.h
util/json_tests.c

Add function `gvm_json_obj_check_str` and use it in `vtparser.c` and `openvasd.c`.
This is a variation on `gvm_json_obj_str` that allows you to retrieve the string field and at the same time get a return value that indicates if the field existed.
Neater than using the repeated cJSON snippets.
As with the similar PRs, this has the nice side effect of removing assignments from `if` conditions.
Note that the function returns 0 if the field exists, and an error value otherwise. Currently the error is always 1, but this style allows us to add more detail to the error value in future, eg if someone wants to know if the field existed but was the wrong type it could return 2.
Similar to /pull/881 for ints.
Follows `gvm_json_obj_str` from /pull/877.

Add: gvm_json_obj_check_str

---

openvasd/openvasd.c

Use `gvm_json_obj_str` in more places in gvm-libs.
Neater.
This is a follow on to /pull/877. I left these out because they're inside `if` checks, so it made the PR harder to understand.
/pull/877 added `gvm_json_obj_str`.

Change: use gvm_json_obj_str more

---

openvasd/CMakeLists.txt
openvasd/vtparser_tests.c

Add test of `openvasd_parse_vt`.
Tests good.

Add: first test of vtparser.c

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.github/build-dependencies.list

Add a devcontainer setup for gvm-libs development
Devcontainers are containers that provide a dedicated development environment for IDEs like VSCode or IntelliJ.
See https://code.visualstudio.com/docs/devcontainers/containers or https://containers.dev/ for more background.

Add a devcontainer setup for gvm-libs development

---

openvasd/openvasd.c
openvasd/vtparser.c

Move assignment statements out of `if` conditions where possible. So
```
if ((a = b))...
```
becomes
```
a = b
if (b)...
```
I'm starting with `openvasd/` because we've been working there recently.
Putting the `=` in the condition is error prone because it's easy to read the `=` as `==`.
Having the `=` in the condition is also harder to read because an extra pair of parens is required around the `=` statement.
This change also makes some duplicate variable inits obvious. Eg in
```
int ret = CURLE_OK;
ret = curl_easy_perform (curl);
if (ret != CURLE_OK)
```
`ret` is being assigned OK just to be assigned again on the next line.
So I've removed these inits where the duplicate init happens soon after. I understand people are trying to be careful but I think these redundant inits should all be …

Change: move assignments out of `if` conditions (openvasd)

---

util/mqtt.c

In the MQTT library, also free the `MQTTResponse` on success.
Previously we were only freeing on error.
Freeing the response only on error is probably OK given the way we're using the API, but we might as well always free the response to be safe.
The documentation gives very little clue about precisely when to use `MQTTResponse_free`.
I see some `malloc`s of properties in the `WAIT_FOR_CONNACK` case in `MQTTClient_connectURIVersion`, which might indicate that on success there is memory to be freed, at least for `MQTTClient_connect5`.

Always free the MQTTResponse

---

util/CMakeLists.txt
util/mqtt.c
util/mqtt_tests.c

Add `mqtt_tests.c`.
At the same time, clear the client field in `mqtt_client_destroy`. This is a very minor change, mostly an excuse to add a test. It's also safe because the mqtt is always freed by `mqtt_client_data_destroy` straight after `mqtt_client_destroy`.
Start of test coverage for mqtt.c.

Add: first test of mqtt.c

---

util/kb.c
util/mqtt.c
util/radiusutils.c
util/serverutils.c
util/versionutils.c

Move assignment statements out of `if` conditions where possible. So
```
if ((a = b))...
```
becomes
```
a = b
if (a)...
```
Putting the `=` in the condition is error prone because it's easy to read the `=` as `==`.
Having the `=` in the condition is also harder to read because an extra pair of parens is required around the `=` statement.
Follow on to /pull/890.

Change: move assignments out of if conditions (util)

---

util/CMakeLists.txt
util/serverutils.c
util/serverutils_tests.c

Add `serverutils_tests.c`.
Adds a lot of gnutls code for a simple test, but hopefully it will be useful for later tests.
Start of test coverage of `serverutils.c`.

Add: first test of serverutils.c

---

util/CMakeLists.txt
util/radiusutils_tests.c

Add `radiusutils_tests.c`.
Start of test coverage for radiusutils.c.

Add: first tests of radiusutils.c

---

boreas/alivedetection.c
boreas/arp.c
boreas/boreas_io.c
boreas/cli.c
boreas/util.c

Move assignment statements out of `if` conditions where possible. So
```
if ((a = b))...
```
becomes
```
a = b
if (a)...
```
Putting the `=` in the condition is error prone because it's easy to read the `=` as `==`.
Having the `=` in the condition is also harder to read because an extra pair of parens is required around the `=` statement.
Follow on to /pull/890.

Change: move assignments out of if conditions (boreas)

---

boreas/util.c
boreas/util_tests.c
util/cpeutils.c
util/versionutils.c

Use `return x;` instead of `return (x);`.
Also add tests of `in_cksum`, for coverage.
Easier if they're all the same.

Nitpick: use consistent return style

---

util/kb.c

Use strchr.
rindex is deprecated.
rindex was removed in POSIX-2008: https://man7.org/linux/man-pages/man3/index.3.html#HISTORY

Change: use strrchr instead of rindex

---

.github/workflows/codeql-analysis-c.yml

Added Docker Hub authentication to GitHub Actions to allow pulling private images like `greenbone/gvm-libs.`
greenbone/gvm-libs Docker image has been moved to private, requiring authentication to pull.

Change: Use Docker Hub credentials to pull private images

---

openvasd/openvasd.c
openvasd/openvasd.h

Add: openvasd_get_performance()
Jira: SC-1039

Add: openvasd_get_performance()

---

CMakeLists.txt
INSTALL.md

Require CMake >= 3.5
CMake 4.0 drops support for CMake < 3.5. Therefore require CMake 3.5 as minimum version to allow using CMake 4.0. All our supported platforms already provide CMake >= 3.5
Fixes #910

Require CMake >= 3.5

---

CMakeLists.txt

Build tests without OPENVASD is enabled
Some tests are only buildable if OPENVASD is enabled. Therefore build these tests conditionally too.

Build tests without OPENVASD is enabled

---

osp/osp.c

Check that `error_msg_entity` exists in `osp_check_feed`.
There was a duplicate `if` condition, and the warning was missing when `error_msg_entity` was missing.
I explored writing a test but the cgreen swallows stdout, so it's a little tricky. I confirmed by adding an abort where the warning would be.
Note that even a simple test of `osp_check_feed` needs some intrusive changes (see test patch below) so I'll leave that out for now.
<details>
<summary>Test Patch</summary>
```patch
diff --git a/cmake/MacroAddUnitTest.cmake b/cmake/MacroAddUnitTest.cmake
index d46739bc..8d88696d 100644
--- a/cmake/MacroAddUnitTest.cmake
+++ b/cmake/MacroAddUnitTest.cmake
@@ -2,5 +2,6 @@ macro(add_unit_test _testName _testSource)
add_executable(${_testName} ${_testSource})
target_link_libraries(${_testName} …
```

Fix: check error_msg_entity in osp_check_feed

---

openvasd/openvasd.c
openvasd/openvasd.h

Fix: port field in result
Jira: SC-1294
Also, fix format with clang-format
While openvasd only handle ports as integers, gvmd still waits for general/Host_Details, general/tcp or general/udp.
This patch handles all these possibilities and set the result port field correctly.

Fix: port field in result

---

openvasd/openvasd.c
openvasd/openvasd_tests.c

Allocate `response` before assigning to `response->code`.
Otherwise a segfault happens when the ID is missing.
Note that these errors would have been shown by the compiler, like this:
```
/home/user/openvasd/openvasd.c:627:22: error: ‘response’ may be used uninitialized [-Werror=maybe-uninitialized]
627 |       response->code = RESP_CODE_ERR;
```
but people have started always initializing variables to NULL in the variable declaration (even when the intention is to initialize the variable later), so we lose these kind of warnings.
First seen for `openvasd_start_scan` in /pull/907.

Fix: allocate response before use in openvasd_stop_scan and openvasd_delete_scan

---

openvasd/openvasd.c

Ensure `response` and `parser` in `openvasd.c` are freed.
Also remove some redundant code.
The memory was leaking.
Hopefully removing the redundant code will make these things more obvious.
First noticed in /pull/907.

Fix: memory leaks of openvasd response and parser

---

util/passwordbasedauthentication.c

Leave the size out of the `asci64` array declaration.
The compiler puts a NULL terminator on the string, so the ascii64 array was one too short. Leaving out the size lets the compiler sort it out.
Closes #924.

Fix: prevent warning about ascii64 buffer being too small

---

agent_controller/agent_controller.c
agent_controller/agent_controller_tests.c

This PR updates the agent_controller_get_agents function to return an empty list when there are no agents, instead of returning NULL.
The previous implementation could return a non-empty or invalid list even when no agents existed. This caused issues in downstream logic expecting an actual list of agents.
GEA-974

Change: agent_controller_get_agents returns empty list instead of null on zero count

---

CMakeLists.txt
util/compressutils_tests.c
util/json_tests.c

The tests will fails because of:
- error: ignoring return value of 'write' declared with attribute 'warn_unused_result' [-Werror=unused-result]
- error: 'ret' may be used uninitialized in this function [-Werror=maybe-uninitialized]

Fix gcc errors

---

COPYING

Update GPLv2+ license text
Use the text from the official GNU web page.
Fixes #932

Update GPLv2+ license text

---

CMakeLists.txt
util/CMakeLists.txt
util/streamvalidator.c
util/streamvalidator.h
util/streamvalidator_tests.c

New utility functions have been added to allow validating the size and checksum / hash of contents of a data stream like a file being read.
This is to be used for validating the integrity of agent installer files.
GEA-963

Add: New data stream validation utilities

---

util/streamvalidator.c

Instead of using G_REGEX_DEFAULT and G_REGEX_MATCH_DEFAULT, 0 is used to indicate no flags.
This is done for backward-compatibility of with older GLib versions.

Fix: Do not use macros for not setting regex flags

---

util/CMakeLists.txt
util/jsonpull.c
util/jsonpull_tests.c

Close leaks in `utils/jsonpull`.
Add the `-fsanitize=address` flag to `jsonpull-test`.
Leaks.
Note that the leaks are only reported when I run `BUILD/util/jsonpull-test` directly. If I run `cmake test` they are missed. Something to do with ENV vars for `make test` perhaps. But the idea is to add `-fsanitize=address` for all tests, so that can wait.
Closes #935

Fix: close leaks in jsonpull

---

base/hosts.c
base/hosts_tests.c
cmake/MacroAddUnitTest.cmake
util/CMakeLists.txt

Always build and run tests with the address sanitizer. This includes:
- fixing a leak in `is_hostname`
- correcting an overwriting error in `gvm_hosts_move_current_host_to_end` that was presenting as a leak
- making sure the tests themselves always free memory. 
It's good to see when something is leaking memory. And this can show up other errors.
Follows /pull/939.

Fix: always build tests with `-fsanitize=address`

---

agent_controller/agent_controller.c

Replaced `cJSON_free` with `g_free` when releasing the payload to ensure the correct memory deallocation function is used. 
Using `cJSON_free` for memory allocated with GLib functions caused a mismatch in allocation/free.
GEA-1126

Fix: change comment of the agent_controller_convert_scan_agent_config_string

---

agent_controller/agent_controller.c
agent_controller/agent_controller.h
agent_controller/agent_controller_tests.c

Remove the period_in_seconds field from the scan agent config data structures
It is no longer supported by the agent controller.
GEA-1255

Change: remove period_in_seconds from scan_agent_config

---

agent_controller/agent_controller.c
agent_controller/agent_controller_tests.c

Replaced the usage of the `Authorization` bearer token header with the `X-API-KEY` header when communicating with the HTTP Scanner.  
The HTTP Scanner already uses API key–based authentication.  
Aligning gvmd with this convention ensures consistency across integrations, avoids confusion between bearer tokens and API keys, and follows the intended authentication mechanism of the scanner.

Change: Switch header token to X-API-KEY

---

agent_controller/agent_controller.c
agent_controller/agent_controller.h
agent_controller/agent_controller_tests.c

Added a new helper function `agent_controller_build_create_scan_payload()` that builds the JSON payload for creating a scan in the agent controller.  
This is required when using the `http_scanner` API, since it expects a properly create-scan payload.  
GEA-1258

add: agent_controller helper to build create-scan payload

---

base/networking.c
base/networking_tests.c

Close some leaks.
Better to be tidy.
Note: this only touches `gvm_routethrough` in the actual library code. I don't see this function in use anywhere.

Fix: close leaks shown by the networking tests

---

http_scanner/CMakeLists.txt

http_scanner misses link to libcjson.
Build fails on clang with  -Wl,--no-allow-shlib-undefined
Allowing to build with shared libs using -Wl,--no-allow-shlib-undefined
https://github.com/greenbone/gvm-libs/issues/960

closes #960; Fix missed link to CJson

---

base/logging_domain_tests.c

Close a leak shown by `-fsanitize=address` in the logging domain test.
Tidier.

Fix: close leak in logging domain test

---

osp/osp_tests.c
util/passwordbasedauthentication_tests.c

Close leaks in `passwordbasedauthentication_tests.c` and `osp_tests.c`.
Found by `-fsanitize=address`.
Neater.

Fix: close leaks in OSP and PBA tests

---

util/versionutils.c
util/versionutils_tests.c

Close leaks in `cmp_versions`.
Found by `-fsanitize=address`.
Also increased test coverage of `cmp_versions`.
Neater.

Fix: close leaks in version utils

---

.docker/prod.Dockerfile
.github/workflows/container.yml

Use new container build push workflow
The workflow is more flexible in the regard of how to build a container image, which tags it should get and which features it should include.
https://jira.greenbone.net/browse/GEA-1139

Use new container build push workflow

---

agent_controller/agent_controller.c
agent_controller/agent_controller_tests.c

Add handling 422 response code for modifying the scan agent config
This response code needs to be handled properly for returning a valid error response
GEA-1278

Add: handling 422 response code for modifying the scan agent config

---

container_image_scanner/container_image_scanner.c
container_image_scanner/container_image_scanner.h
container_image_scanner/container_image_scanner_tests.c

Added scan_id to container_image_target
It is required to start a scanner task properly
GEA-1254

Add: Added scan_id to container_image_target

---

agent_controller/agent_controller.c
agent_controller/agent_controller_tests.c
http/httputils.c
http/httputils.h
http/httputils_tests.c
http_scanner/http_scanner.c

Close a leak in `gvm_http_response_cleanup`. And close leaks in the agent controller tests themselves.
Shown by `-fsanitize=address`.
Neater.

Fix: close leaks shown by agent controller tests

---

.github/workflows/container.yml

Don't build versioned container image for testing and oldstable
Also don't use the latest container image tag for testing and oldstable builds.

Don't build versioned container image for testing and oldstable

---

container_image_scanner/CMakeLists.txt

Tune linking of container_image_scanner.
Without cjson ldflags ldd will compain about undefined symbols.
Before:
```
ldd -r -d /usr/lib64/libgvm_container_image_scanner.so.22.29.0
linux-vdso.so.1 (0x00007fa6784c6000)
libeatmydata.so => /lib64/libeatmydata.so (0x00007fa6784b3000)
libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007fa678364000)
libc.so.6 => /lib64/libc.so.6 (0x00007fa67818b000)
libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007fa6780e9000)
/lib64/ld-linux-x86-64.so.2 (0x00007fa6784c8000)
undefined symbol: cJSON_CreateObject    (/usr/lib64/libgvm_container_image_scanner.so.22.29.0)
undefined symbol: cJSON_Print   (/usr/lib64/libgvm_container_image_scanner.so.22.29.0)
undefined symbol: cJSON_AddStringToObject       (/usr/lib64/libgvm_container_image_scanner.so.22.29.0) …
```

Tune linking of container_image_scanner

---

base/CMakeLists.txt
base/settings_tests.c

Add tests of `base/settings.c`.
Increases coverage. Shows leaks.

Add: tests of base/settings.c
